### ISSUE TITLE
Non-standard capability support.

### ISSUE THREAD

**Issue by iGovindY** [CESNET/netopeer2#1046]
Hi All,

does `netopeer2`/`sysrepo` provide a way to add support for non-standard capability ?

- if yes which version? `libyang1` branch or `devel`?, 
  also how to use such functionality.
  All I could find out was `nc_server_set_capability()` which is only used by netopeer for standard capability.

if not, is this planned anytime?

**Comment by iGovindY** [comment]
Hi Michal,

my understanding is with yang1.1 support, features are not advertised in `hello` only capabilities are, for feature, client needs to do get on `/modules-state/module` after NETCONF establishment right?

can netopeer2 advertise feature support in `hello` also?

**Comment by michalvasko** [comment]
Well, you will never get YANG 1.1 modules (or their features) in `hello` because it is defined that way and adding explicit capabilities for them is just trying to bypass the specification. You should rely on `ietf-yang-library` data instead. I was, obviously, talking about YANG 1.0 modules, they are included in `hello` with all the enabled features.
