### ISSUE TITLE
Not getting notification when giving path.

### ISSUE THREAD

**Issue by Shubham-dash** [CESNET/netopeer2#1064]
Hi everyone 
I am writing an application in which I want to get notification of a particular node present in the yang model for that I am giving a path in my code that I am mentioning down but the issue is in the path due to which error is coming please give a solution for this. I am attaching the yang node for which I want notification and path I am giving.

Yang model : o-ran-laa-operations.yang 

path for notification as macro :
```
#define laa_notif      "/o-ran-laa-operations:measurement-result"
#define laa_notif_node1 laa_notif "/band-result[band-number='BAND_46_SUBBAND_A']"
#define laa_notif_node2 laa_notif_node1 "/measurement-success"
#define laa_notif_node3 laa_notif_node1 "/failure-message"
```
 

Node : 
```
leaf failure-message {
      when "../measurement-success='false'";
      type enumeration{
        enum TIMEOUT {
          description "Timed out waiting for measurement completion.";
        }
      }
      description "This value indicates the detailed error message for failure of the measurement at O-RU.";
    }

```

**Comment by michalvasko** [comment]
Please learn to include relevant information in these issues and do not create duplicates. The very least, you could have included the error message you got but based on that you should know what the problem is. So you probably do not see it, if you have this code in a *sysrepo* callback. If you put `ly_log_options(LY_LOLOG | LY_LOSTORE);` at the beginnig of your callback and `ly_log_options(LY_LOSTORE);` at the end, you should see the message.
