### ISSUE TITLE
Netopeer2 server ssh callhome, key exchange timeout

### ISSUE THREAD

**Issue by ankit7gup** [CESNET/netopeer2#1080]
Hi Michal, 

We are getting below issue of SSH key timeout while trying to connect the Netopeer2-server to a netconf client(Own application using same version libnetconf2 and libssh).

The netconf client is in listening mode on port 4334, both ports are enabled for telnet, but still the server cannot successfully connect to the client.

[INF]: LN: Trying to connect via IPv4 to 20.20.1.200:4334.
[INF]: LN: Successfully connected to 20.20.1.200:4334 over IPv4.
[INF]: SR: Session 110 (user "root", CID 145) created.
**[ERR]: LN: SSH key exchange timeout.**

Netconf client status using netstat:

[root@bqf911300134 ~]# netstat -anlp | grep 4334
tcp 0 0 **20.20.1.200:4334 0.0.0.0:* LISTEN** 150197/./client_app

Netopeer2 version being used:

Netopeer2 CLI 2.0.64
Compile time: Oct 22 2021, 20:47:14

Libssh version used: 
0.9.5

Please suggest. Thanks!

Regards,
Ankit

**Comment by michalvasko** [comment]
> both ports are enabled for telnet

Not sure if that is a typo but, obviously, we are talking about SSH here, not telnet. I seem to remember someone having a similar problem but I do not know what caused and how to solve it, never seen it myself. Does the client print anything, do you even see its output?

**Comment by ankit7gup** [comment]
Telnet uses the TCP as base similar to SSH callhome, so we tested that over port 4334. On the client side, we receive the message and connection and then looses it while it goes into a retry mode. Same thing is happening in a loop.
Not sure how to debug it further, we are kind of stuck at this point here.

Any suggestion will help. Thanks!

**Comment by michalvasko** [comment]
> [INF]: LN: Trying to connect via IPv4 to 20.20.1.200:4334.
[INF]: LN: Successfully connected to 20.20.1.200:4334 over IPv4.

This means that the TCP/IP connection works just fine, please forget about telnet, this is an SSH problem. I have searched all the issues mentioning this error (you can too) but even if the issue was closed by the author (so I assume they solved it), they never bothered to mention the solution so I really cannot help you but I do think it is a problem on your side. All I can suggest is to **make sure** you are using *libssh* 0.9.5 on both ends and maybe try even the latest 0.9.6 even though to my knowledge 0.9.5 should be fine.

**Comment by ankit7gup** [comment]
ok, Thanks Michal. I am using libssh0.9.5 only on both sides. Will try to run server client exmaple using libssh APIs as a next thing to debug further. 
If I found a solution will let you know.

**Comment by kaizhang0124** [comment]
@ankit7gup hi ankit. I found u close the issue. could u tell me how to resolve it? thanks
