### ISSUE TITLE
Is there any way/ API exposed to know callhome connection status?

### ISSUE THREAD

**Issue by senrajib** [CESNET/Netopeer2#110]
Hi Michal
Is there a way/ API exposed(sysrepo,libnetconf,netopeer-server anywhere?) to monitor established callhome connections? We , in code, are writing into sysrepod running datastore to configure callhome and having netopeer notified to build callhome connections.
We want our application monitor callhome connections and take appropriate actions.

-Rajib

**Comment by michalvasko** [comment]
Hi Rajib,
no, there is currently nothing to allow you to monitor Call Home sessions. We designed *libnetconf2* based on the [server schema draft](https://tools.ietf.org/html/draft-ietf-netconf-netconf-client-server-01#section-3.1) (I know there is a newer revision, we will be updating it if some important changes are made), which actually defines exactly how the server should behave in which situation. Currently, the new session is given to the application using a callback and it can do what it wants with it (netopeer2 `main.c:np2srv_new_session_clb`). That is the place to add actions on a new session creation. When the session is disconnected for whatever reason, *libnetconf2* does not do anything. Only when you free this session, a new session is tried to be established based on the Call Home settings. So, before calling `nc_session_free()` (netopeer2 `main.c:np2srv_del_session_clb`), you can do what you want. I am thinking now that this is perhaps not the correct behavior and the session should be reestablished as soon as the current one disconnects, but maybe this way it suits you better because it gives you some control over it.

So, is this enough or you would require to react to some other events on the session? Actually, all the events are returned from `nc_ps_poll()` so you are free to behave differently for each of them (netopeer2 `main.c:worker_thread`). Sounds fine?

Regards,
Michal

**Comment by senrajib** [comment]
Hi Michal

Our application communicates to netopeer2 to configure callhome by writing into sysreo running DS. We dont link to libnetconf2. Netopeer server runs as a separate process. We are certainly missing oppotunity to make use of netopeer2 main.c:np2srv_new_session_clb .

I believe nc_ps_poll() is responsible to poll on all the established NC sessions. And main.c:np2srv_del_session_clb is used when nc_ps_poll() returns NC_PSPOLL_SESSION_TERM on a session. So when ,let's say , Callhome TCP transport is disturbed by any means(i,e  making physical i/f down) will that be reflected in nc_ps_poll() as well?

If i am free to wish, would expect ietf-netconf-server data model to support GET of callhome status :) . And when netopeer2 detects any connection issue, have that info available with the sysrepo , let sysrepo update connection status for an endpoint.

**Comment by michalvasko** [comment]
Hi Rajib,
based on what you said it seems, you can only communicate with *netopeer2-server* using *sysrepo*. So, if you set `ietf-netconf-server` configuration to perform Call Home, the server should behave as described in the `ietf-netconf-server` module meaning it starts connecting and reconnects if the session is terminated for any reason. But you will not learn about any of this, only that the server started connecting when you set the configuration.

You are free to wish for anything, but you would have to implement this yourself (which should not be too difficult, but you need to write your own simple module with this status information or one that augments it into another). Actually, there are notifications defined that are sent when a session changes its status. You would have to know what sessions are Call Home ones, but I think that could be learned some way. However, I am currently working on notifications and they are not fully functional yet, so you would have to wait a few days, maybe a week for this. Still, I think you should get all the information form these notifications (look into `ietf-netconf-notifications`, all of those will be generated except for `confirmed-commit`).

Regards,
Michal
