### ISSUE TITLE
[ERR]: NP: Getting GID grp entry failed (Group not found).

### ISSUE THREAD

**Issue by LoveCPro** [CESNET/netopeer2#1153]
Q: netopeer2-cli connect success,but operation is error;

$ netopeer2-cli
> connect 
Interactive SSH Authentication
Type your password:
Password:
> get
ERROR
        type:     application
        tag:      access-denied
        severity: error
        path:     /ietf-netconf:get
        message:  Access to the requested protocol operation or data model is denied because authorization failed.
>

netopeer2-server log：
[INF]: NP: Session 2: thread 3 event new RPC.
[ERR]: NP: Getting GID grp entry failed (Group not found).
[INF]: NP: Session 2: thread 1 event new RPC.
[INF]: NP: Session 2: thread 1 event reply error.

Does it have to be root to log in via netopeer2-cli？Why can't netopeer2-server get GID?

**Comment by michalvasko** [comment]
> Why can't netopeer2-server get GID?

I have no idea, you have some weird user configuration on your system. In the code there are first all group IDs retrieved for a user and then the group name for each GID is retrieved, which fails in your case. Seems like an inconsistency and best I could do is improve the error message so that you see what is the user and GID that fails.
