### ISSUE TITLE
Netopeer2 server re-establishing disturbed Callhome connection after a long time 

### ISSUE THREAD

**Issue by senrajib** [CESNET/Netopeer2#118]
Hi Michal

I had configured a periodic callhome connection . When callhome connection was established, i brought down the connection by pulling out the cable. After 2 mins i plugged in the cable again. Observed Netopeer2 server re-established the disturbed connection after 1 hour. Would you please comment on this behavior?

-Rajib

attaching Configuration and  debug logs 

[ietf-netconf-server.zip](https://github.com/CESNET/Netopeer2/files/870322/ietf-netconf-server.zip)
[debuglog.zip](https://github.com/CESNET/Netopeer2/files/870323/debuglog.zip)

**Comment by michalvasko** [comment]
Hi Rajib,
based on your running configuration my guess is that the reason is you configuring `reconnect_timeout` (which is an obvious typo on the module so I fixed it in our modules, I didn't think it could cause any problems) instead `reconnect-timeout` so the default `60` was used.

Regards,
Michal

**Comment by senrajib** [comment]
Hi Michal
Many thanks for the quick fix. I shall take latest code fix from devel then. 

-Rajib

**Comment by michalvasko** [comment]
No, I haven't fixed anything, I have already changed the leaf name in our modules before, so you need to change the leaf name in the configuration from `reconnect_timeout` to `reconnect-timeout`.

Michal

**Comment by senrajib** [comment]
Hi Michal
Ok.
But i could only find a leaf named 'reconnect_timeout' for periodic connection type in ietf-netconf-server data model .
-Rajib

**Comment by senrajib** [comment]
Hi Michal
As i read in below link, leaf named  'reconnect_timeout' is defined for periodic connection of NETCONF client and leaf named  'reconnect-timeout' is defined for periodic connection of RESTCONF client .

https://tools.ietf.org/html/draft-ietf-netconf-server-model-09

-Rajib

**Comment by michalvasko** [comment]
Hi Rajib,
you misunderstand me, but alright, I updated *netopeer2* repository `ietf-netconf-server` module so that it is the exact module from the RFC draft. To use it, it would probably easiest for you to reinstall all of *sysrepo*, *keystored*, and *netopeer2-server*. The fastest way is probably to simply open *ietf-netconf-server* YANG module, which is located in your sysrepo `repository` directory somewhere and manually change `reconnect-timeout` to `reconnect_timeout`. Then the issue should be fixed.

Regards,
Michal

**Comment by senrajib** [comment]
Hi Michal
Thank you for the update!
I believe Netopeer2 ,sysrepo code now complies with latest ietf-netconf-server.yang  data model . I mean in code we would use reconnect_timeout instead of reconnect-timeout. In that case i will take new code from Netpeer2-server and sysrepo devel branch.

-Rajib

**Comment by senrajib** [comment]
Hi Michal
This issue is not resolved in latest devel branch code.  I am using a 'periodic' connection type with reconnect_timeout value '30' . Once callhome connection is established, i pulled out the cable for a minute and plugged in again. Far end client system had callhome connection cleaned up. But in our side callhome connection was still in 'ESTABLISHED' state forever. Netopeer2 server never attempted to establish it again. In fact , Netopeer2 server did not come to know about the connection disruption at all.

-Rajib

**Comment by michalvasko** [comment]
Hi Rajib,
as I have mentioned before, if the disconnection is not detected in Network layer (kernel), we have no chance of detecting it in Application layer. Keep-alive may have been included in the standard drafts for this very reason, but unfortunately it is not implemented yet and it will not be anytime soon. So I do not know how to help you.

Regards,
Michal
