### ISSUE TITLE
Failed logs are coming when running netopeer2-server -d -v3 & 

### ISSUE THREAD

**Issue by bkumarrr** [CESNET/netopeer2#1193]
Hi 
When we are starting netopeer2-server some failed logs are coming but netopeer2-cli is able to connect with netopeer2-server 
Below is the logs :
**[INF]: LY: Resolving derived type "union" failed, it will be attempted later.**
Kindly specify the above log significance

**Comment by michalvasko** [comment]
Log significance is expressed by its severity. `INF` stands for informational so you are perfectly fine ignoring it. Also, it is just a *libyang* message, which are even less significant.

**Comment by bkumarrr** [comment]
Hi @michalvasko 
Thanks for your response
**Can you please tell me its meaning ,what it is searching for ?**

**Comment by michalvasko** [comment]
Fine, although I do not understand why you care. The message simply says that when a YANG module was being compiled, there was a `union` found that had some nested type name, which was not known at the moment. But as it says, it will be attempted later when all the possible types are known in case it is a forward reference to the type. And since you have not seen any error afterwards, it means the type was ultimately resolved.

**Comment by bkumarrr** [comment]
Thanks @michalvasko
