### ISSUE TITLE
sysrepo callback function is not getting called 

### ISSUE THREAD

**Issue by deepthib29** [CESNET/netopeer2#1258]
Hi Michael,

1. have generated the xml files and configured using import command am able to see the data using export command but if any configuration changes occurs, when i changed the values and then pushed the xml file using edit-config, configuration has not changed.
2. sysrepo call back functions are also not called.

could you please reply for above points.
Thanks,
Deepthi

**Comment by michalvasko** [comment]
That does not really makes sense so you must have something basic wrong in your setup. Do you perhaps have an older version of *sysrepo* still installed and you end up with 2 instances of the datastore? Not sure what else it could be.

**Comment by deepthib29** [comment]
am using v1.4.140(SO V5.6.56). is it ok or need to update?

**Comment by michalvasko** [comment]
Ideally, you should be using *sysrepo* v2 but this is a core functionality that is not working for you and there is no bug that can be causing this, I think, so v1 should be fine. I really cannot help you without knowing exactly your use-case but I do not know what details to ask because it is impossible to decide what is relevant and what not.

**Comment by calvinjolinux** [comment]
Maybe you can try the example https://github.com/sysrepo/sysrepo/blob/master/examples/application_changes_example.c
