### ISSUE TITLE
Donot get callback for lock/unlock rpc on the local db.

### ISSUE THREAD

**Issue by rosy8** [CESNET/Netopeer2#126]
Hi Michal,

Currently while taking lock/unlock , it takes the lock at the netopeer and sysrepo db.
But in our case we also need to perform lock/unlock operation at our database level too.
But right now we donot get any callback for these rpc.   
Would appreciate if you could give me any suggestion to encounter this issue .

Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
currently, it is probably not possible without modifying our code, so the simplest approach is adding your DB locking code into `op_lock()` and `op_unlock()`. But, it is possible that there will be a better way, it will depend on how NACM will work, which I am going to look at. Will let you know.

Regards,
Michal

**Comment by rosy8** [comment]
Hi Michal,

Thanks for the clarification. 
Yeah please let me know once its ready.

Reagrds,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
it actually seems no changes will be required because of NACM, so there will be no better way of achieving what you need. Maybe you can cope up with something else, but, requiring least changes to the code, you could create a separate source file including `common.h`. This will enable you to modify `np2srv.ly_ctx` and to replace our callback function `op_lock()`/`op_unlock()` with your one, which will first do your stuff and then call the original functions. Nevertheless, this function switch will need to be performed as part of server flow, so you will have to modify its code.

Regards,
Michal

**Comment by rosy8** [comment]
Hi Michal,

Is there any  update related to this (Getting the callback at the application level while executing lock/unlock operation ) ?

Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
as you may have learned, we are currently working on new *sysrepo* so new features can be added. However, the problem with the obvious solution (adding the possibility to subscribe to them using *sysrepo*) is that in that way there would be 2 callbacks for one RPC (one from *netopeer2*, one from your application) and that is not legal because there needs to be one reply generated.

Are you sure your use-case is valid? `<lock>` and `<unlock>` RPCs are supposed to operate on locks for NETCONF datastores, no other proprietary databases. Please explain it more so that we can decide whether the use-case is generic enough and we want to support it or not. I can imagine a solution when there would also be "passive" RPC subscriptions that would just receive the RPC input but will not be allowed to generate the output.

Regards,
Michal

**Comment by rosy8** [comment]
Hi Michal,

Thank you for replying back.

The things which I was trying to do is to take the local db lock along with sysrepo db lock in 
one RPC req- RPC reply)  . 

Basically trying to treat those two locks as one lock  and do that as part of one atomic operation. 

By looking at the code I could see that i can add a  new wrapper over op_lock and subscribed the same as  callback to lock  rpc op.  However, in that case it will work on the Netopeer level. To take the lock on our local db, I need few extra libs etc which is not available at the netopeer  . 

So to overcome that if the same RPC callback somehow reaches up to the application level (just like in case of edit-config )  . 

Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
I have noted your use-case and we will try to support it (in the not-too-near future). But, it is not a simple use-case if it is meant to work reliably so it is not a priority. For now adding the functionality into *netopeer2* is your best bet because it **should** be only on the NETCONF level. If you try to execute `<lock>` using a sysrepo application, it will fail as there are no handlers subscribed to it (by default). It should be received only using NETCONF and so handled only by *netopeer2*.

Regards,
Michal
