### ISSUE TITLE
Query about key generation

### ISSUE THREAD

**Issue by anithacp** [CESNET/Netopeer2#127]
We are trying to integrate sysrepo, netopeer2 server, libyang, libnetconf2 into an exisiting Openwrt build. Our binary image size was around 5.4 MB before the integration and now has increased to around 6.8 MB post integration with PMA modules including openssh. Currently dropbear to log into the device. Since netopeer server requires openssh package,we have the following questions

1. Can the existing dropbear keys be used instead of openssh? I tried the following and wasn’t successful.
```
root@XXX:/# dropbearkey -t rsa -f id_rsa
Generating key, this may take a while...
Public key portion is:
root@XXX:/# dropbearkey -y -f id_rsa | grep "^ssh-rsa " >> authorized_keys
root@XXX:/# cp authorized_keys /etc/keystored/keys/ssh_host_rsa_key.pub.pem
root@XXX:/# sysrepocfg -d startup -i /etc/sysrepo/xml/stock_key_config.xml ietf-keystore
The new configuration was successfully applied.
```
However the client connection to server failed
```
 # ./cli/build/netopeer2-cli
> connect --ssh --port 830 --login root --host 192.168.1.1
nc ERROR: Starting the SSH session failed (Socket error: Connection reset by peer).
cmd_connect: Connecting to the 192.168.1.1:830 as user "root" failed.
```
2. Private key generated by SSH is used as is while openssl is used to generate the public key from the SSH public key. Why is this needed? Is there a way to use the SSH public key directly without requiring the openssl package?
```
root@XXX:/# ls -l /etc/ssh/
-rw-r--r--    1 root     root        246880 Apr 11 04:11 moduli
-rw-------    1 root     root           227 Apr 11 04:37 ssh_host_ecdsa_key
-rw-r--r--    1 root     root           175 Apr 11 04:37 ssh_host_ecdsa_key.pub
-rw-------    1 root     root           399 Apr 11 04:37 ssh_host_ed25519_key
-rw-r--r--    1 root     root            95 Apr 11 04:37 ssh_host_ed25519_key.pub
-rw-------    1 root     root          1679 Apr 11 04:37 ssh_host_rsa_key
-rw-r--r--    1 root     root           395 Apr 11 04:37 ssh_host_rsa_key.pub
-rw-r--r--    1 root     root          3640 Apr 11 04:11 sshd_config
root@XXX:/# cp /etc/ssh/ssh_host_rsa_key.pub /etc/keystored/keys/ssh_host_rsa_key.pub.pem
```
Above also cause connection failure.

Above questions arises mainly because we have a size limitation on the embedded device. We want to limit the image size to less than 6.5MB. We are using development branches for all the modules, updated to latest as of April 10, 2017.

Thanks,
Anitha

**Comment by michalvasko** [comment]
Hi Anitha,

1.) You did not include the error of the server (client says that the server disconnected and that makes sense, because I believe it encountered an error), but I think it may have failed to find the private part of the host key. I don't know what format *dropbear* uses, but it could be supported if you set it right. It all comes down to being supported by *libssh*.

2.) The whole situation about the keys is currently quite complicated because the draft model we are using for this is not designed well. It should improve with the next revision, but we must wait until then with any updates. But, *OpenSSH* should not be strictly required, it is only used if it is installed to simplify the whole installation. If you don't have it, the installation will not fail, just tell you that you need to set the host key yourself.

Now, I would like to briefly explain server configuration. Without it, the server will use one SSH host key (which can be set during installation) and always listen on `0.0.0.0:830` for SSH connections. None of this can be modified in any way without modifying server code. The other option is to support configuration, which then requires to have `keystored` installed and `sysrepo-plugind` running. With this all the standard NETCONF server options can be changed.

So, how to reduce the final image size? I have 2 ideas that should make a difference. If you are fine with having the server without configuration (you can easily change the default configuration, but you will never be able to modify it run-time, only after changing the code and recompiling it), you do not have to use `sysrepo-plugind`, `keystored`, and therefore even `openssl` application. I would advise this at least for now, until the keys are managed in a more reasonable way. The other idea is changing the build of *libyang*, *libnetconf2*, and maybe also *libsysrepo*, so that all of them are linked to *netopeer2-server* statically. If you then `strip(1)` it, you should save a considerable amount of space.

Regards,
Michal

**Comment by anithacp** [comment]
Hi Michal,

Thanks a lot for the detailed explanation. We resolved the issue by using the existing dropbear keys to generate the SSH RSA host key. Also as suggested by you, we have removed the keystored as we don’t foresee changing of the server configurations.
```
dropbearconvert dropbear openssh /etc/dropbear/dropbear_rsa_host_key /etc/ssh/ssh_host_rsa_key
```
Thanks and regards,
Anitha.
