### ISSUE TITLE
netopeer2-server crashes when connected over TLS channel

### ISSUE THREAD

**Issue by mister-potter** [CESNET/netopeer2#1286]
Hello,

I am working on simple netopeer2-server and netopeer2-cli TLS connection establishment to get started with. I have successfully compiled the sources as per the README doc and installed them in the required sequence.

netopeer2 stack version: v2.1.36

### problem statement:
I am able to start the server with debug logs. When I try to connect using the command line tool with below given command, server crashes (attaching the logs: [netopeer2-server-error-log.txt](https://github.com/CESNET/netopeer2/files/9860226/netopeer2-server-error-log.txt))

Could you guide me on what's causing this and how to fix?

### netopeer2-cli command:
`connect --tls --host localhost --cert client.crt --key client.key --trusted ca.pem`

**Comment by mister-potter** [comment]
### Additional information:
- SSH is disabled - Only TLS channel is supported in this experiment
  - Installed the tls_listen/_truststore/_keystore xmls before starting the server
- Server crashes after last line printed in the attached log - Signal 11 is raised (SIGSEV)

**Comment by michalvasko** [comment]
Not sure what the problem may be but seems like something on your end because the use-case is really basic. Note that you only need to run the server with `-d -v2`, no need for debug output, it is just clutter. Then, please run the server with `valgrind`, it should immediately show the nature of the problem.
