### ISSUE TITLE
netopeer2-cli connection type

### ISSUE THREAD

**Issue by lilililizheng** [CESNET/netopeer2#1298]
Hey, I was wondering if netopeer2-server uses ssh key authentication to log in, but netopeer2-cli does not implement this method. As I understand it, I tried the following method for ssh login on the client.

The client generates the public-private key pair, and I place the client's public key in /root/.ssh/authorized_keys. I then received the following error.

![image](https://user-images.githubusercontent.com/106649263/201814098-3bcdff7b-d5c2-4f88-9cd3-0c4cfbb6e0e8.png)

I seem to have misunderstood, all the configuration of netopeer2-server should be stored in the yang model, I guess.

**Comment by michalvasko** [comment]
*netopeer2-cli* certainly implements SSH `publickey` authentication method, you just need to configure the keys with the command `auth keys add ...`. And yes, for the keys to also be accepted by the server, you need to put the public key into the `authorized_keys` file, but they must conform to the `OpenSSH` format. What you have seems like the PEM format, which is why it is not accepted. Just search how to convert from one format to another.
