### ISSUE TITLE
Why did "get-config" add "<data>" tags which edit-config doesn't like?

### ISSUE THREAD

**Issue by qupfer** [CESNET/netopeer2#1343]
Hi,
I'm new to the netconf/syrepo/xml topics, so please be indulgent if my questions seem obvious.

I just compiled/installed the "basics" (libyang,sysrepo,libnetconf and netopeer2) and try to play with the tools.
One of the first things was to try export and import configs. So I did something like that (assuming an unmodified exported config should be valid for import)
```
get-config --source running --out out
edit-config --target running --config=out
```
which always fails with an internal error

```
ERROR
	type:     application
	tag:      operation-failed
	severity: error
	message:  Internal error (/root/build_sysrepo/yang/src/printer_lyb.c:226).
	
``` 

My first assumption  was permission problems (even connected as root).
But it seems the (additional?) <data> Layer added by get-config is the problem. Removing first an last line in the "out" file (<data> and </data> and the edit-config command success.  

Can someone explain what is the reason for them and how can I avoid them?

And another question: is there a reason the style of --out and --config differs? or just historical? :-D

Thanks

**Comment by jktjkt** [comment]
Please post netopeer2's log as well as versions of the individual components.

**Comment by qupfer** [comment]
Thanks for your answer:
netopeer2 log:
```
# get-config --source running --out out
[INF]: SR: Published event "rpc" "/ietf-netconf:get-config" with ID 2 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:get-config" "rpc" event with ID 2 priority 0 (remaining 1 subscribers).
[INF]: SR: Successful processing of "rpc" event with ID 2 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 2 priority 0 succeeded.
[INF]: NP: Session 1: thread 2 event new RPC.


# edit-config --target running --config=out
[ERR]: SR: Internal error (/root/build_sysrepo/yang/src/printer_lyb.c:226).
[ERR]: NP: Failed to send an RPC (libyang error).
[INF]: NP: Session 1: thread 1 event new RPC.
[INF]: NP: Session 1: thread 1 event reply error.
```
[out.zip](https://github.com/CESNET/netopeer2/files/10550475/out.zip)


Versions (todays master branch of:
https://github.com/CESNET/libyang
https://github.com/CESNET/libnetconf2.git
https://github.com/sysrepo/sysrepo
https://github.com/CESNET/netopeer2.git

``` 
[root@c1 ~]# netopeer2-server -V
netopeer2-server 2.1.49

sysrepoctl -V
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v2.2.36 (SO v7.13.13)




```

**Comment by michalvasko** [comment]
Of course someone completely new tries something completely simple yet what no one else tried. The internal error should be fixed in latest *libyang* but you will just see a proper error of `data` not being a known node. I do understand the impulse that made you try this use-case but it is simply not valid. For **every** RPC the CLI simply prints its [output](https://github.com/CESNET/netopeer2/blob/master/modules/ietf-netconf%402013-09-29.yang#L417). When executing `edit-config`, the CLI gives you a way of populating the [config](https://github.com/CESNET/netopeer2/blob/master/modules/ietf-netconf%402013-09-29.yang#L528). Generally, it is only a coincidence that the output of one RPC can be used as the input for another so yes, you would have to remove the `data` element for it to work.

**Comment by qupfer** [comment]
Merci 🙏 
That’s exactly what I wanted to know.
