### ISSUE TITLE
Stuck on confirmed commit after app restart or reboot

### ISSUE THREAD

**Issue by synther** [CESNET/netopeer2#1345]
Hi, let me share my observations, would glad to get feedback on it.

Netopeer2 version: 2.1.49

## Case 1. Can’t issue a confirming commit after app’s restart

1. Make some changes to `candidate`.
2. Issue a confirmed commit using `<persist>`

    ```
    <rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="a079805e-0245-48ea-a50e-6c8c6a24612a">
      <commit>
        <confirmed/>
        <confirm-timeout>240</confirm-timeout>
        <persist>31e3cddf-bb23-4822-8d86-ffb125dafceb</persist>
      </commit>
    </rpc>
    ```

3. Restart netopeer. E.g. due to a crash.
4. Issue a confirming commit with `<persist-id>`.

    ```
    <rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="234fe223-35fd-42a0-8752-ebceea0a2ed5">
      <commit>
        <persist-id>31e3cddf-bb23-4822-8d86-ffb125dafceb</persist-id>
      </commit>
    </rpc>
    ```

Instead of confirming the commit, I will get the error:
```
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="234fe223-35fd-42a0-8752-ebceea0a2ed5">
    <rpc-error>
        <error-type>application</error-type>
        <error-tag>invalid-value</error-tag>
        <error-severity>error</error-severity>
        <error-message xml:lang="en">Commit does not match pending confirmed commit.</error-message>
        <error-info>
            <bad-element>persist_id</bad-element>
        </error-info>
    </rpc-error>
</rpc-reply>
```

You will get the same error if you try to rollback a confirmed commit with `<cancel-commit>`.

At this point the confirmed commit is stuck, can’t either confirm or cancel it. The only option is to wait until the timeout expires.

I can see what’s happening here. After restart, `ncc_try_restore` restores a timer for rollback, but not a `commit_ctx.persist` which is empty after restart. And a correct `persist-id` from the NC client gets rejected by Netopeer.

## Case 2. Can’t issue a confirming commit after device’s reboot

Another case is related to an app’s restart.

According to the RFC6241:

> If the device reboots for any reason before the confirm timeout
> expires, the server MUST restore the configuration to its state
> before the confirmed commit was issued.

Formally, this requirement is met, configuration is restored (just because `running` had no chance to be copied to `startup` before restart). However, after reboot a confirmed commit is stuck in the same way as in Case 1. You have to wait until the timeout expires.

Additionally, things would get worse if a device didn’t have an RTC and the app started before NTP worked out. In that case, `time(NULL)` returns year 1980 during `ncc_try_restore` and a restored timeout would expire in 43 years from now.

I can imply the correct behavior is not to recover a persist confirmed commit at the app’s start if the commit was issued before the current boot-up. It doesn’t make any sense to restore the timeout after reboot at all because we know that the configuration is already lost. We can’t either confirm changes or cancel them anyway.

**Comment by michalvasko** [comment]
Thanks for the report, according to the paragraph you quoted, I think the rollback should occur immediately after a restart, so that is how I changed it.

**Comment by synther** [comment]
Thank you for a rapid reply. 

The fix doesn’t cover the case when the server app is just restarted. For example, the server crashes and it’s got restarted by systemd. Technically, it’s possible to restore a pending commit, but we just discard it instead.

Is it ok for you?

**Comment by michalvasko** [comment]
Okay, I have interpreted `device reboot` as server restart because there is no way for the server to know what is actually happening. But I still think that is the intention of that paragraph, to restore the configuration. So yes, I think that now it behaves in compliance with the specification.

**Comment by synther** [comment]
I think they mean `device reboot` as a physical device reboot, not a server. Because a server restart should be transparent to a user. Nobody cares when the server restarts and why as long its observable behavior complies with the specification. 

I can think of a few ways how to detect whether it’s a restart or reboot:
1. Create a dummy file at some tmpfs on app’s start. E.g. `/tmp/…` or `/dev/shm/…`. If the file already exists — it’s a restart. 
2. Track `/proc/sys/kernel/random/boot_id` change.

**Comment by jktjkt** [comment]
I don't think that a NETCONF server should be tracking boot IDs, ever. In fact, on our embedded appliances we're trying hard to purge the whole state of the SHM once Netopeer2 restarts simply to try to speed up service restoration. If `netopeer2-server.service` tried to guess boot state, we would have to patch that out due to reliability concerns. It's just one extra moving part to QA for.

I think that the intention of the RFC is clear: the state is kept *in memory* and there's no need to save it to a non-volatile data store to persists across "restarts", whatever that is.

Of course the situation with sysrepo+netopeer2 is a bit more complex because there actually *is* a bit of shared state which persists across service restarts, but not across reboots -- the SHM, and quite often also the state of the `running` DS. I can imagine that Netopeer2 might want to consult something in the `running` to check for these "semi persistent" confirmed commits. But if there is no file backing the `running` DS, then surely the system must have "restarted" (no matter if it was a reboot or a service-restart-with-aggressive-cleanup-of-SHM).

But honestly, this is extra work that's a bit harder to test, and the only benefit is that you'll get the capability to restart a single service. The real question is -- why are you restarting the NETCONF server process, and why do you want to persist confirmed commits over that?

**Comment by michalvasko** [comment]
> I think they mean device reboot as a physical device reboot, not a server.

We have always treated it as being the same thing.

> Because a server restart should be transparent to a user. Nobody cares when the server restarts and why as long its observable behavior complies with the specification.

The server can hardly restart transparently for the user. All the existing NETCONF sessions are terminated and until the server restarts, it is not reachable and cannot be connected to.

The current behavior is compliant with the specs and I prefer it, seems @jktjkt does as well. So unless you can prove otherwise, it will stay this way.

**Comment by synther** [comment]
I can see the only case to persist a confirmed commit, it's a possibility to recover after a server crash. If a server crash happens after `<commit>` but before confirming `<commit>` or `<cancel-commit>`. I've described this case in my initial post, Case 1. Of course, it's only possible if `<persist>`/`<persist-id>` is used. 

I don't think recovering after a crash case would be on RFC. Ideally, the server does its best job to recover everything it can recover after a crash. Sure, some things can be restored, some not. 

I don't question the new behavior; I do agree it complies with the spec. My [comment](https://github.com/CESNET/netopeer2/issues/1345#issuecomment-1420952556) was whether you wanted to extend it with a fancy super smart intelligent crash recovery. After the discussion I understand this is something that complicates the server internally and QA process a lot, and simply not worth it. 

I have no further questions. Thank you for the fix.
