### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by lilililizheng** [CESNET/netopeer2#1386]
hei, I want to know if the subscription has a timeout mechanism. For example, in the callback of my change subscription, there is a handler that is in some kind of problem and keeps looping, causing the lock resource to keep being occupied. This will cause all rpc requests on the client to fail, I guess because the lock has been occupied.

**Comment by michalvasko** [comment]
There are timeouts everywhere but if your change callback is stuck, there is no magical way of fixing such a subscription. All requests will simply keep timing out until that callback returns or that whole applications crashes, otherwise it is assumed the callback is simply performing a long task. We cannot really assume it is buggy.
