### ISSUE TITLE
ietf-netconf get-config from a client like smo throws error

### ISSUE THREAD

**Issue by jayanta-sarkar** [CESNET/netopeer2#1422]
Hi, when I post ietf-netconf get-config with below input from a netconf client (smo)

input - source xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"
candidate xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"

Getting below error
500 null HTTP/1.1
Access-Control-Allow-Credentials: true
Cache-Control: must-revalidate,no-cache,no-store

even though it can be seen in the smo log that tere is some data replied from server which is
keystore xmlns="urn:ietf:params:xml:ns:yang:ietf-keystore" and netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server"

Could you please help me out where I went wrong ?

**Comment by jktjkt** [comment]
Netopeer2 is a server which talks the [NETCONF protocol](https://datatracker.ietf.org/doc/html/rfc6241). What you've shown are some headers which belong to the [HTTP protocol](https://datatracker.ietf.org/doc/html/rfc9110). I also have no clue what the "smo" is.

I'm afraid you'll have to rephrase the question in order to get useful feedback. What are you trying to achieve, what is happening, and why do you think Netopeer2 is at fault?

**Comment by jayanta-sarkar** [comment]
Thanks Jan Kundrat,
Thanks for your time to respond.
It seems this is an UI issue.
SMO is a orchastrator which have Restconf(http) interface and can translate to corresponding Netconf messages.
So, it seems this error is from Restconf.
At Netopeer2 level if I find such issue will get back. As of now closing this issue.

Warm Regards,
Jayanta
