### ISSUE TITLE
Questions about the version of the ietf-crypto-types module

### ISSUE THREAD

**Issue by Agao404** [CESNET/netopeer2#1474]
Hi @michalvasko,

The file "ietf-crypto-types@2019-07-02.yang" in the source code is officially released by IETF NETCONF (Network Configuration) Working Group, right?
I can't find the corresponding version in the official ORAN Yang file, so I would like to check with you.
I see a lot of different content.
![image](https://github.com/CESNET/netopeer2/assets/104612620/40a2dec0-7678-4110-830f-fb10e2074e9e)

**Comment by michalvasko** [comment]
No `ietf-crypto-types` YANG module has been officially released, unfortunately. It was simply taken from then-current RFC draft and you can see it is a different revision than what ORAN is using. So yes, there may be differences and I am not sure what is your question. In any case, we are working on a new *libnetconf2* version that will be using the modules from the current drafts, including this one. We were hoping they will actually get published as RFCs by the time we finish it but we are not that certain anymore.

**Comment by Agao404** [comment]
Thanks for your reply.
I just couldn't find a corresponding version of the Young model in the ORAN release, so I was wondering where you got the Young model from.
If this inconsistent version of the Young model is encountered when writing a configuration file with reference to ORAN's Young model, wouldn't it cause some errors to be generated, such as node not found or something like that.
Because I look at this Young model as an example in ORAN 12.0, they are using the version below, and some of the nodes in it have changed.
![image](https://github.com/CESNET/netopeer2/assets/104612620/8499b63d-ec1b-443d-ba03-3aa34bb64d71)

**Comment by michalvasko** [comment]
Based on the revision, [this](https://datatracker.ietf.org/doc/html/draft-ietf-netconf-crypto-types-10#section-2.2) is where the modules is from. The module is not being installed by *netopeer2* so you should be able to use all ORAN modules with the other revision of this module. But it may require changing some imports of `ietf-crypto-types` to include the exact revision because the modules are completely different and without the revision, effort is made to always import the same revision of a module.

**Comment by Agao404** [comment]
Okay, thanks.
