### ISSUE TITLE
Question: Can notification drive client side sysrepo callback?

### ISSUE THREAD

**Issue by BillYJT** [CESNET/netopeer2#1518]
Hi.

I want to use the netopeer client and server in an SDN controller and agent scenario, where the agent(server) creates some notification that drives some subscribed callback logic on the controller(client) side.

I would like to know if the provided netopeer-cli implementation automatically propagates the received notification to the client-side sysrepo subscribed callback. I also see the mentioning of this [project](https://github.com/CESNET/netconf-cli) which mentioned local interaction with sysrepo. But would like some clarification.

Any input is very much appreciated. Thanks!

**Comment by michalvasko** [comment]
To answer, no, *netopeer2-cli* does not notify locally subscribed *sysrepo* applications when it receives a notification. What you are trying to do is not officially supported so you will have to find your own way of doing so. For example, writing your own simple NETCONF client (or modifying *netopeer2-cli*) that would just send received notifications to *sysrepo* should not be difficult.

**Comment by BillYJT** [comment]
Hi, Michal. Thanks again for the prompt and concise response. 

Is there any particular part of the netopeer2-cli that you could point me to that could be a good place to interface with sysrepo? If not, it's also fine, I guess I will just need to learn the code.

**Comment by michalvasko** [comment]
You could just send the notification to *sysrepo* when it is received in the CLI in its [callback](https://github.com/CESNET/netopeer2/blob/master/cli/commands.c#L213).

**Comment by jktjkt** [comment]
Since you mentioned SDN, I assume that you're after an architecture where there's a NETCONF server, and you're writing a client which connects to the NETCONF server and which listens for notifications. Right? If that's the case, you can ignore sysrepo completely because it's "just an implementation detail of a server"; your application code won't really be aware of sysrepo because the communication is all defined by the NETCONF standard.

In that scenario, you'll need a NETCONF client library, such as [libnetconf2](https://github.com/CESNET/libnetconf2). That library has features for waiting for NETCONF notifications. (If you prefer C++, there's also the C++ wrapper around that, the [libnetconf2-cpp](https://github.com/CESNET/libnetconf2-cpp).) Once you've learned how to use that library, just write some code which uses that library for notification processing, and do whatever you want to do with that information.

**Comment by BillYJT** [comment]
Thank you both, Michal and Jan. My question is answered.
