### ISSUE TITLE
Unable to connect using netopeer2-cli

### ISSUE THREAD

**Issue by hrmnboparai** [CESNET/netopeer2#1519]
Hey I have hosted the server on the same machine that I am trying to connect with netopeer2-cli. In the process I am getting the following Error as described in the attached media. Can anyone help me around this

**Comment by michalvasko** [comment]
That is the first time I see such an error but it seems to have been generated by *libssh*, it does not like some SSH system configuration files. I do not think I can help you, try to find out what exactly those files are and fix them if you can.

**Comment by jktjkt** [comment]
Since this only affects the *client* (whose functionality is very limited anyway), and not the NETCONF server at all, there's a simple workaround -- start the server with the `-U` flag to listen on a UNIX socket, and connect the client through that. That will also skip authentication and use your local UID, but it might be a viable way to get you playing with the SW.

The root cause is that libssh is trying to be compatible with the configuration of the OpenSSH client `ssh(1)`. Maybe there are some settings in `/etc/ssh/ssh_config` or `~/.ssh/config` which make libssh unhappy.

**Comment by hrmnboparai** [comment]
Thanks michalvasko and jktjkt
Although this socket method solves the issue for the timing but I think it will not be a viable method if I have to connect from some other machine. I will try to figure out the ssh thing and will let you know the results.
