### ISSUE TITLE
Can't import ssh_callhome.xml to sysrepo

### ISSUE THREAD

**Issue by dkahn-yt** [CESNET/netopeer2#1547]
Hi,

I have installed netopeer2 v2.1.71 to ubunut vm and I can connect the netopeer2-server form netopeer2-cli and it works well.

But I tried to import the example_configuration/ssh_callhome.xml to sysreop, it's failed with following error.

$ sysrepocfg --import=ssh_callhome.xml -v3
[INF] Connection 2 created.
[INF] Session 2 (user "dkahn", CID 2) created.
[ERR] Invalid leafref value "genkey" - no target instance "/ks:keystore/ks:asymmetric-keys/ks:asymmetric-key/ks:name" with the same value. (Data location "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='default-client']/endpoints/endpoint[name='default-ssh']/ssh/ssh-server-parameters/server-identity/host-key[name='default-key']/public-key/keystore-reference".)
[ERR] Validation failed.
sysrepocfg error: Replace config failed (Validation failed)

I don't change any server configuration but I should do something before importing "ssh_callhome.xml"?

please let me know what I missed?

Thanks and regards,
Dokeun

**Comment by Roytak** [comment]
Hi, by doing just `sysrepocfg --import` the whole datastore will be replaced, but you want to keep `ietf-keystore` data, because ssh_callhome.xml references it and hence the operation fails. So either specify the module you want to operate on `sysrepocfg -I ssh_callhome.xml -m ietf-netconf-server` or, instead of replacing the data, just edit it `sysrepocfg -E ssh_callhome.xml -m ietf-netconf-server` (this will keep the default listen config).

**Comment by dkahn-yt** [comment]
Really thank you. I didn't catch that the whole datastore is replaced. ^^;
I used "--edit" and it's running now. :)
Thanks again.
