### ISSUE TITLE
Upgrade Netopeer2 version 1.1.70 to version 2.2.28, Issue with openssl v3.3.2

### ISSUE THREAD

**Issue by DiepHieu99** [CESNET/netopeer2#1655]
My product system device OS is RHEL 8 was installed netopeer2 version 1.1.70 and can run with openssl v1.0.1. When I tried to upgrade netopeer2 to version 2.2.28 , I have to build libnetconf with openssl v3.0.0 above. So far I try to edit the CMakeList to force build with lower version lead to failed created lib binary. But build with openssl v3.0.0 above is OK. Other modules and services in my devices still depend on openssl v1.0.1 then update openssl to v3.0.0 above and some of them cannot run because some feature in v1.0.1 has been deprecated. In conclusion, the question is what is the level issue impact on system and other modules/services when try to update openssl v3.0.0 ? 

![update_list](https://github.com/user-attachments/assets/22fdbefc-11de-4ccb-8b07-1209557e2d1d)

**Comment by michalvasko** [comment]
I do not understand what the question has to do with our project(s). If you have problems with dependencies, just use an older version of *netopeer2*/*libnetconf2*, there is nothing else you can do. But the right thing to do is to update all the other packages that still depend on OpenSSL < 3.0.0 because that OpenSSL version is obsolete, no longer maintained, and therefore a possible security risk.

**Comment by DiepHieu99** [comment]
Thank for your advise, I ask to figure out what impact on the system device when trying to update openssl to version > 3.0.0

**Comment by DiepHieu99** [comment]
Thank for your advise, I ask to figure out what impact on the system device when trying to update openssl to version > 3.0.0
