### ISSUE TITLE
notification subscription still does not work 

### ISSUE THREAD

**Issue by frimpler** [CESNET/Netopeer2#179]
Hi,
this refers to commits of netopeer2: 52f5b77 and sysrepo: 7aa2f18 (which are the current ones today at master branch). 
The solution for issue https://github.com/CESNET/libyang/issues/356 has only partially improved the "subscribe" problem for notifications! 
Mainly, the changes in client_library.c:3515+3543 (set xpath to 0 if no leading "/" and check whether xpath==NULL) and op_notifications.c:240 (provide the plain module name w/o "/" as xpath) lead to the fact that no subscription record can be found in the event of a notification.
If I was sure, where the way will go, I'd provided a solution by myself, but I don't understand why the prefixing of the module name with "/" has been removed. Maybe you could explain...

**Comment by michalvasko** [comment]
Hi,
you are correct, in current `master` branches the notifications do not work properly. We will make a bugfix release of *sysrepo* next week that will address this and some other serious bugs, which will also include a merge of `devel` to `master`. Until then you can use the `devel` branch where it should work properly (https://github.com/sysrepo/sysrepo/issues/922).

Regards,
Michal

**Comment by frimpler** [comment]
Hi Michal, 

thanks for this information. 
Concerning this issue itself I have a little concern/complain: You quickly closed this issue, but in fact it is not yet solved at master branch - which I explicitly addressed. I have beside and later on noticed, that also other already closed issues addressed this problem (e.g.https://github.com/CESNET/libyang/issues/356). I'd prefer, if I could track available error corrections based on the open/close status of the issue. This way it would save all of us time to analyse or answer again and again, that things are already known. At least this is the way we track errors in my company... What do you think?

Regards,
Frank

**Comment by michalvasko** [comment]
Hi Frank,
we are generally always developing on `devel` branches, but because of the problem you mentioned we merge bugfixes to `master`. However, with *sysrepo* the matter is more complicated because we merge into `master` only on a release.

I am closing already solved issues so that we can properly track them and leave opened only unsolved issues, in whichever branch. I believe that if you want to actively participate in the development, which I consider creating issues to be, you have no reason not to use the `devel` branch. `master` branch is meant for people who simply want to deploy our applications and not be bothered by API changes or new bugs.

So, I think for your purposes (having most recent, usually most bug-free revision) `devel` suits better and if you always pull all our repositories before working with them, you should be fine.

Regards,
Michal

**Comment by frimpler** [comment]
My point here is, I'm working in "two worlds" (as probably other contributors do, too): For contributions, the "devel" branch is of course the one which counts, but I pull also more stable versions from "master" which I later on have to integrate in our company's systems. Therefore, found or blocking errors will be related of course to the master branch.
In general, I expected the "devel" branch to be the development/contribution (or "input") branch and the master branch to be the delivery (or "output") branch which always needs to be more stable than the devel branch (at least this is the case in my "other" world). 
However I don't want to tell you how to work...just to give you kind of feedback :-)

**Comment by michalvasko** [comment]
I tell you what, for every issue in *sysrepo* fixed in `devel` and not merged into `master` I will create an issue (if not opened in *sysrepo*, yours is in *netopeer2*, for example) which will stay opened until the merge, deal? For other projects, this problem should not occur.

**Comment by frimpler** [comment]
great! Deal :-)
(at least we should start to try it that way)
