### ISSUE TITLE
Netopeer2 startup robustness

### ISSUE THREAD

**Issue by mikaabra** [CESNET/netopeer2#182]
Currently netopeer2-server can end up in situation where it will not start:

netopeer2-server[6874]: Unsupported SSH key algorithm "ssh-ed25519".
netopeer2-server[6874]: Failed to enable nodes depending on the "local-users" ietf-system feature.
netopeer2-server[6874]: Server init failed.

This configuration passed the YANG model (because it doesn't validate against what encryption algorithms are supported or not) and with this validated and applied configuration, netopeer2-server now refuses to start. 

I would like instances where this happens to instead just skip those configuration leafs that are invalid (in this case, ignore this specific key), and continue the startup.

Are there other cases where this might happen?

**Comment by michalvasko** [comment]
*netopeer2* communicates with *sysrepo* and calls *libnetconf2* functions during configuration initialization so it may not even be a problem with the configuration itself when something fails so the following is my idea of how it may work. There will be 2 possible configurations *netopeer2* will use. We can call one the **default config**, the other **sysrepo config**.

**sysrepo config** depends on having *sysrepo-plugind* with *keystored* running and *sysrepo* itself must have *ietf-netconf-server* module installed. If this is true, it will try to retrieve the configuration from *sysrepo* and configure itself based on it. If it succeeds, everything is fine. If not there are 2 options. Either, on encountering any error, it will immediately give up and fall back to the **default config** or it will continue (skip that configuration node) and only if, at the end, it will detect that it cannot start with whatever that it managed to configure it will use the **default config** instead. I vote for the former solution because it is easier to implement, there is no vagueness regarding what is acceptable configuration and what is not, and it will also prevent a situation when there will be something seriously wrong with the configuration but the server will use it anyway, possibly causing some security issues.

**default config** will be used if the basic requirements are not met (*sysrepo-plugind* not running or *ietf-netconf-server* not present in *sysrepo*) or if the **sysrepo config** was not applied properly, as described previously. This default configuration will be modifiable during compilation, which it currently is not. It should be just a backup or for testing purposes so I do not think too many options need to be available. Two main parameters need to be configured, on what interface (address/port) to listen on and what authentication to use. So, you could set the address/port (only one pair should be sufficient or not?). Then, you could set the authentication to use system users, allow a specific public key (only one again?), or even maybe one specific username/password (perhaps too insecure?). Since this **default config** would became more important, it would be required during compilation for the user to explicitly decide what will it contain and refuse to compile (install) without that.

Thoughts?

Regards,
Michal

**Comment by jktjkt** [comment]
> So, you could set the address/port (only one pair should be sufficient or not?)

I believe that it should listen on both IPv4 and IPv6 by default, which is apparently [doable](https://stackoverflow.com/a/1618259/2245623) with just one socket. However, I have no idea if it can be represented in just one address/port pair in YANG for the corresponding module.

**Comment by michalvasko** [comment]
@jktjkt If you are talking about the **default configuration**, I should have probably mentioned one important difference, it is not modeled as YANG data, only **sysrepo config** is, so there is no issue with what you are proposing. However, in connection to what I have written, there would be no default address to listen on, so you could, let's say, specify the address to listen on or explicitly set that you want to listen on all IPv4 and IPv6 addresses. If the socket option would be enabled by default on your system, there would be no difference between using that special option or setting the listening address to `::`.

Regards,
Michal

**Comment by michalvasko** [comment]
Hi,
we also have to decide what to do if *sysrepod* is not running during *netopeer2-server* startup and it fails to start it. Probably there is nothing else to do but quit because without *sysrepod* a NETCONF client can establish a NETCONF session and that is it. No NETCONF operation support means the session is useless.

Regards,
Michal

**Comment by mikaabra** [comment]
Hi,
would it make sense for netopeer2 to stay around and retry the sysrepod connection until it succeeds? I'm ok with netopeer2 not listening to the configured netconf port without connection to sysrepod. So I don't know what is best, to stay alive and keep trying to connect to sysrepod, or quit and rely on the startup scripts noticing this and restarting netopeer2 until it succeeds.

Also, what happens if netopeer2 is already started and sysrepod is restarted? Will netopeer2 quit then, when sysrepod stops working?

We need a robust system where on a whole, the system tries to keep netopeer2 and sysrepod working as a unit, and restarts connections/processes in case something fails. If this should be done by the processes themselves or their startup scripts is a design choice we should all agree on so it's clear for everybody how it's supposed to work.

**Comment by michalvasko** [comment]
Hi,
I am about to commit *netopeer2* changes that make it never quit whatever the state of the connection to *sysrepod* is (unless it failed to connect to *sysrepod* at the start). However, I have not initially realized that the usefulness of this feature is quite low because if a connection to *sysrepod* is attempted and *sysrepod* is not running, it is started first. Either it succeeds, when the server can normally resume work or it does not, in which case I would say something is really wrong and consider it a fatal error. Then there is no real use for the server to wait for a miracle causing *sysrepod* to suddenly be able to start, a manual fix is very likely needed. After that the whole software suite can be manually restarted, no connection should be accepted until then.

Regards,
Michal

**Comment by jktjkt** [comment]
We've been using these systemd service unit files for managing `sysrepod` and `netopeer2-server`. We're tracking the `-devel` branches, so we've got our fair share of crashes in both daemons. That's why this configuration deliberately uses a shotgun approach and ensures that upon any failure in any of these daemons, everything gets killed and then re-started in the correct order form scratch.

I think that this ordering and safeties belong to the init system, which is why I decided to leverage system'd features for this.

### /usr/lib/systemd/system/sysrepod.service
```
[Unit]
Description=Sysrepo YANG configuration storage and management
After=syslog.target network.target
PartOf=netopeer2-server.service
StartLimitIntervalSec=0

[Service]
Type=forking
ExecStart=/usr/bin/sysrepod
PIDFile=/var/run/sysrepod.pid
PrivateTmp=yes
PrivateDevices=yes
ProtectSystem=yes
ProtectHome=yes
SystemCallArchitectures=native
Restart=always

[Install]
WantedBy=multi-user.target
```

### /usr/lib/systemd/system/sysrepo-plugind.service
```
[Unit]
Description=Sysrepo YANG configuration storage and management
Requires=sysrepod.service
After=sysrepod.service

[Service]
Type=forking
ExecStart=/usr/bin/sysrepo-plugind
PIDFile=/var/run/sysrepo-plugind.pid
PrivateTmp=yes
ProtectSystem=yes
ProtectHome=yes
SystemCallArchitectures=native

[Install]
WantedBy=multi-user.target
```

### /usr/lib/systemd/system/netopeer2-server.service
```
[Unit]
Description=A NETCONF server on top of sysrepo
After=syslog.target network.target sysrepod.service
Requires=sysrepod.service
PartOf=sysrepod.service
StartLimitIntervalSec=0

[Service]
Type=forking
ExecStart=/usr/bin/netopeer2-server
PIDFile=/var/run/netopeer2-server.pid
PrivateTmp=yes
PrivateDevices=yes
ProtectSystem=yes
ProtectHome=yes
SystemCallArchitectures=native
Restart=always

[Install]
WantedBy=multi-user.target
```

I would much prefer `netopeer2-server` to die early and not attempt to "do magic". I also do not want `sysrepo-plugind` or `netopeer2-server` to start `sysrepod` on demand if it isn't running. If it is not running, it's a serious problem in our system, and if the init system wasn't able to fix that, trying to run `sysrepod` outside of the corresponding init environment will only make matters more confusing for us.

**Comment by mikaabra** [comment]
Our use-case is a bit different. For us, netopeer2/sysrepod is running on a device, and this is the only way to manage the device. There is no CLI access, because security policy might not allow that. So there is "oh, it's ok for netopeer2/sysrepo to die, someone can fix this some other way". This is the only way. If netopeer2/sysrepo dies and doesn't work, only way to get management back would be to factory default the device and start over. This requires someone to be physically close to the device and press a button. This also will be a service outage for the customer. It might even require a truck roll in some markets.

**Comment by michalvasko** [comment]
Fair enough, when, for example, *sysrepod* crashes, *netopeer2-server* will detect it and part of `sr_connect` call is also *sysrepod* start if it is not running.

All I am saying is that if *sysrepod* fails to be started this way, there is nothing for *netopeer2-server* to wait for because without *sysrepod* it is unable to do anything and like you said, it will not start on its own (or will it?). Also, I am just trying to cover all the cases, it has never happened to me that *sysrepod* would fail to start, generally speaking.

Regards,
Michal

**Comment by jktjkt** [comment]
@mikaabra I think that our use case is actually very similar (we are working with DWDM equipment with limited out-of-band access). We're currently working on a dual-rootfs setup where an appropriate response to a repeatedly failing boot, or services failing many times in a row, is a revert to the other rootfs, and an automated re-flash of the failing partition.

My point is that the first line of defense against transient failures can be the init system. It notices that either Sysrepo or Netopeer2 failed, and it tries restarting them a few times with a timeout.

If the init system does that for us, we don't need to implement a similar feature in all daemons.
