### ISSUE TITLE
sample code for using TLS support 

### ISSUE THREAD

**Issue by dileepravindran** [CESNET/Netopeer2#190]
we know libnetconf2 supports TLS . 
Is there a sample code from  netopeer2 how to set up and establish a connection between server-client?

**Comment by michalvasko** [comment]
Hi,
I am not sure what exactly do you want, but if only to establish a TLS connection between *netopeer2-server* and *netopeer2-cli* then it is included, otherwise you will have to adjust those steps for your use-case. All the required information and configuration is in `netopeer2/server/configuration` directory, detailed instruction in the `README.md` there.

Regards,
Michal
