### ISSUE TITLE
netopeer2 server- client over TLS

### ISSUE THREAD

**Issue by dileepravindran** [CESNET/Netopeer2#193]
Has any one tried netopeer2 server- client over TLS?.
 i'm trying to establish  connection b/w netopeer2 server- client over TLS. i tried following the steps mention in https://github.com/CESNET/Netopeer2/tree/master/server/configuration and was not succesful
 Any  inputs to achieve would be helpful.

Thanks

**Comment by michalvasko** [comment]
Hi,
you say you were not successful, a bit more details please. There are exact steps in the `README` how to configure it, which step did not produce the expected result? Also, it would be best if you used `devel` versions but it should work in `master`, too.

Regards,
Michal

**Comment by dileepravindran** [comment]
i'm using the master version . i was trying with existing crt file Netopeer2/server/configuration/tls/server.crt. It a bit confusing as i'm new to this TLS enabling . 

could guide me on this?

**Comment by michalvasko** [comment]
I wrote the `README` so that I do not have to guide every person separately. If you are completely new to TLS, you have 2 choices. Either you first try to understand all the basics (which is not that trivial) or you simply follow my guide word-by-word without knowing exactly what it is you are doing. In the long run, if you want to change anything and not just use my examples, you must have some understanding of TLS.

If you decide to study something first, I suggest you first learn how certificates work (certificate authorities, trust anchors and certificate chains, ...). Then, it is best to at least read [RFC 7589](https://tools.ietf.org/html/rfc7589) even if not to full understanding of everything. Next, I would definitely advise to look at the YANG models we are using, descriptions of the valid fields. The models are `ietf-keystore`, `ietf-tls-server` (and the main module `ietf-netconf-server`), and most importantly `ietf-x509-cert-to-name` (which configures how usernames are obtained when using TLS, the main difference in comparison to SSH). These models can be found in `netopeer2/modules`.

If, on the other hand, you want to make it work before anything else, you should be fine with the `README`. You want to look at the section *Listen/TLS* and there are links to a few other sections that are relevant. There you have exact steps of what to do, I have nothing more to add, really.

Regards,
Michal

**Comment by dileepravindran** [comment]
okay . thanks!

In the README file we have 
"In the XML tls_listen.xml, which you need to send to the server, you will see that again all IPv4 interfaces are listened on and the port used si the default TLS one, 6513. Other than that, the server will use the certificate test_server_cert we configured in the step before."

XML tls_listen.xml, which you need to send to the server? how is this done?

**Comment by michalvasko** [comment]
Hi,
it is short for "send to the server as the content of an `edit-config` operation". The point is, it must be set as the server configuration and it is prepared as an input file for `edit-config` command of *netopeer2-cli*. Still, you can get the configuration to the server also some other ways. For instance, if you have no daemons (*sysrepo*, *netopeer2-server*) running, you can use *sysrepocfg* to directly modify `ietf-netconf-server` startup configuration. When you then start *netopeer2-server*, it will listen and expect TLS transport connections.

Regards,
Michal

**Comment by dileepravindran** [comment]
using the below command (sysrepo, netopeer2-server daemons not running).

sysrepocfg --import=load_server_certs.xml --format=xml --datastore=startup ietf-keystore
The new configuration was successfully applied.

and then 

 sysrepocfg --import=tls_listen.xml --format=xml --datastore=startup ietf-netconf-server. getting the below error

[ERR] (srcfg_import_datastore:836) Data returned by sysrepo are not valid: Leafref "/ietf-keystore:keystore/ietf-keystore:private-keys/ietf-keystore:private-key/ietf-keystore:name" of value "ssh_host_rsa_key" points to a non-existing leaf. (/ietf-netconf-server:netconf-server/listen/endpoint[name='test_ssh_listen_endpt']/ssh/host-keys/host-key[name='test_ssh_listen_key']/public-key)
Errors were encountered during importing. Cancelling the operation.

**Comment by michalvasko** [comment]
Hi,
that is quite expected since you erase the `ssh_host_rsa_key` from *ietf-keystore* configuration using the first command. Try repeating all the steps but use `--merge` instead of `--import` (if you have used `edit-config`, you would not have this problem).

Regards,
Michal

**Comment by dileepravindran** [comment]
i tried --merge instead  of --import, it still the same . 

could you please provide me with all commands to be executed with sysrepocfg to get started before "connect -tls"

**Comment by michalvasko** [comment]
Hi,
I will not keep helping with you basic things when it is obvious you have no idea what you are doing. You want to have `ietf-keystore` startup configuration a merge of `/netopeer2/keystored/stock_key_config.xml` and `/netopeer2/server/configuration/load_server_certs.xml`, there are many ways of achieving this and I have already mentioned at least 2. You can look at the configuration using `sysrepocfg --format=xml --editor=vim --datastore=startup ietf-keystore`, for example (you can even directly edit it this way).

Regards,
Michal

**Comment by dileepravindran** [comment]
okay . i missed configuring  /netopeer2/keystored/stock_key_config.xml . 

sysrepocfg --merge=../../keystored/stock_key_config.xml --format=xml --datastore=startup ietf-keystore
sysrepocfg --merge=load_server_certs.xml --format=xml --datastore=startup ietf-keystore
sysrepocfg --merge=tls_listen.xml --format=xml --datastore=startup ietf-netconf-server

netoper2-server  started  with Listening on 0.0.0.0:6513 for TLS connections.

Thanks for the help

**Comment by michalvasko** [comment]
Great, `stock_key_config.xml` is set during installation, but you have removed it when you imported another file, so you did not miss anything.

Regards,
Michal
