### ISSUE TITLE
source IP for initiating the connection from server 

### ISSUE THREAD

**Issue by rosy8** [CESNET/netopeer2#199]
Hi Michal
Is there any way we can configure the source IP of call home connection initiated from netconf server ?

**Comment by michalvasko** [comment]
Hi,
I am not sure what you are asking, you want to spoof your source address?

Regards,
Michal

**Comment by rosy8** [comment]
Hi Michal,

Thanks for responding back.
As per our design call home application should initiate the connection with pre configured src Ip of an interface .

Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
I think this more of a TCP/IP issue than NETCONF one. So there are no configuration options that would enable adjusting such parameters. I would suggest you modify the priorities of your interfaces so that the correct one is used. I am not even sure you can adjust this in any standard application in general, you are at the mercy of `connect(2)`, which has no parameter to specify the source interface in any way, as far as I know.

Regards,
Michal
