### ISSUE TITLE
SSH_SERVER_KNOWN_CHANGED

### ISSUE THREAD

**Issue by gidiciaul** [CESNET/Netopeer2#20]
Please ,

Can you explain me why the message SSH_SERVER_KNOWN_CHANGED arise and cause the ERROR below?

In Attach it is possible to examine the log of  comnands:

  . verb 3

  . connect localhost --port 6002 --ssh --login smo 

of Netopeer2 Client .

ThankS in advance

Giuseppe Di Ciaula

[Netopeer2Client.Out.txt](https://github.com/CESNET/Netopeer2/files/474984/Netopeer2Client.Out.txt)

**Comment by michalvasko** [comment]
Hi,
that should mean that you previously connected to that server and then saved its host key as trusted. What happened now is you tried to connect and the server has sent you a different host key than before. This could, in theory, mean that some part of your network was compromised and you are actually connecting to another server. This error protects you from sending your password to this fake server. However, in practice, this usually means that the host keys of the server simply changed and since you are connecting to localhost, this is obviously the case. To fix it, just delete all the known localhost keys from your known_hosts SSH file. You can do this using **netopeer2-cli** as well.

Regards,
Michal

**Comment by gidiciaul** [comment]
Thank Michal!

Best Regards

Giuseppe
