### ISSUE TITLE
Query: Is it possible to disable TLS and keep SSH in netopeer2-server?

### ISSUE THREAD

**Issue by swathins079** [CESNET/Netopeer2#201]
TLS is not being used in the implementation so want to disable that. please let me know the steps if tls can be disabled.

Regards,
Swathin

**Comment by michalvasko** [comment]
Hi Swathin,
*netopeer2* supported transports are completely decided by the supported transports of installed *libnetconf2*. You can learn how to modify transport protocols of *libnetconf2* in its README (to turn off TLS, use `-DENABLE_TLS=OFF` for `cmake`). It is on by default because it makes no difference as far as dependencies are concerned (*OpenSSL* is a sole requirement for TLS, but is also a dependency of *libssh*, which is required for SSH).

Regards,
Michal

**Comment by swathins079** [comment]
Thanks Michal for the quick reply.

I am aware of the flag -DENABLE_TLS in libnetconf2. When I turned off the TLS in libnetconf2, I am getting compilation errors in netopeer2-server.

Regards,
Swathin

**Comment by swathins079** [comment]
It will be great if we can have a flag in netopeer2-server to disable TLS just like the flag -DENABLE_TLS in libnetconf2.

Thanks,
Swathin

**Comment by michalvasko** [comment]
Hi,
you should no longer get compilation errors when compiling *netopeer2-server* having installed *libnetconf2* without TLS support.

Regards,
Michal
