### ISSUE TITLE
Query: Is it possible to integrate dropbear ssh with Netopeer2-server?

### ISSUE THREAD

**Issue by swathins079** [CESNET/Netopeer2#272]

**Comment by michalvasko** [comment]
Hi,
I suppose you mean Dropbear SSH client to communicate with *netopeer2-server*. Then it most certainly should be possible because both applications communicate using SSH protocol. However, *netopeer2-server* uses NETCONF protocol on top of SSH and I believe Dropbear does not support it. Still, you should be able to establish connection, authenticate and ask for `netconf` subsystem. You can then create NETCONF messages "manually" (I tried it a few times with OpenSSH `ssh(1)`) but I would definitely discourage you from that as it is quite painful.

Regards,
Michal

**Comment by swathins079** [comment]
Thanks Michal for the quick response. I will implement it with the openssh.

Regards,
Swathin
