### ISSUE TITLE
Call-Home -> operation-not-supported

### ISSUE THREAD

**Issue by P-KH** [CESNET/netopeer2#290]
Hello,

We are using the docker version of the netopeer2-server to the test the call-home functionality using edit-config RPC call.

Here is the XML we are using as user-rpc:
```xml
<edit-config
    xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"
    xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">

  <target>
    <running/>
  </target>

   <config>
     <subscription>
      <identifier>22</identifier>
      <encoding>encode-xml</encoding>
      <stream>
        <name>NETCONF</name>
        <receiver>
          <address>1.2.3.4</address>
          <port>1234</port>
        </receiver>
      </stream>
    </subscription>
 </config>
</edit-config>
```

And here is the response we get:

`ERROR
	type:     application
	tag:      operation-not-supported
	severity: error
	message:  Request could not be completed because the requested operation is not supported by this implementation.`

Any idea what causes this issue? Actually the call-home functionality  should be supported.

**Comment by P-KH** [comment]
Here are the versions we are using:

`netopeer2-server 0.5.22
compile time: Jun  6 2018, 12:15:59`

`Netopeer2 CLI 2.0.47
Compile time: Jun  6 2018, 12:16:06`

**Comment by michalvasko** [comment]
Hi,
I am not sure where you got that `edit-config` or from which model it is supposed to be, it is unknown to me. For correct Call Home information look at `netopeer2/configuration/README`.

Regards,
Michal

**Comment by P-KH** [comment]
The edit-config above was from the following draft:
[https://tools.ietf.org/html/draft-ietf-netconf-netconf-event-notifications-09](url)
See: A.3.1.  Creating Configured Subscriptions

If I understand it correctly, the defaults are all set within the docker environment, so that I do not need to the edit-config part? Is that correct?

My next question is:
How can I generate a notification using netopeer-cli to test if the call-home mechanism actually works?

Thanks in advance

**Comment by michalvasko** [comment]
Hi,
firstly, you omitted the XML namespaces and hence I could not know from which model the data are supposed to be (neither does the server). More importantly, we have not implemented the new notifications, they are still a draft anyway. What is implemented you can find in `netopeer2/modules`. This whole concept of some implicit Call Home connection is new and we do not support anything like that. If you want Call Home, you must properly configure it. How to do that is mentioned in `netopeer2/configuration/README`.

To answer now your question, you cannot really generate a notification using `netopeer2-cli` because we are using *sysrepo* as the notification store, you can send the notification to it and it will get passed to `netopeer2-server`. And we only support standard Call Home meaning a mechanism of a NETCONF server initiating connection to a NETCONF client. Other that this it is a normal session. Notifications are completely independent (like they were before this draft).

Regards,
Michal

**Comment by P-KH** [comment]
Hello,

Is there an easy way to test the Call Home functionality?

Thanks

**Comment by michalvasko** [comment]
Hi,
just apply the configuration in `netopeer2/server/configuration/ssh_callhome.xml` and start the server, it should try periodically to connect to the configured client. Then, you can use *netopeer2-cli* command `listen` and the server will connect to it.

Regards,
Michal

**Comment by P-KH** [comment]
Hi,

Thanks for your quick reply.
How can I apply `netopeer2/server/configuration/ssh_callhome.xml`?
Sorry but I'm pretty new to netopeer :)

Best regards.

**Comment by michalvasko** [comment]
Hi,
that is fine but you cannot expect me to walk you through everything from basics, I also have some work to do :) Quick answer, either locally writing it into *sysrepo* startup datastore using *sysrepocfg* or remotely via NETCONF using standard *netopeer2-cli* `<edit-config>` targetting running configuration (but this change will not be persistent -> disappear after *sysrepo* restart).

Regards,
Michal

**Comment by P-KH** [comment]
Hello Michal,

Do you know how we can send a notification to sysrepo? to a specific module?
Is there a tool or program for testing that?

I found the following link:
[http://www.sysrepo.org/static/doc/html/start_page.html](url)

Is it possible to test this functionality without implementing a sysrepo client and calling
` sr_event_notif_send`?

Best regards

**Comment by michalvasko** [comment]
Hi,
yes, there is a tool for testing that, look into `sysrepo/examples` and try `event_notif_sub_example`. And no, it is not possible to test this functionality without a client actually sending the notification using `sr_event_notif_send` but that example will handle that for you.

Regards,
Michal
