### ISSUE TITLE
Netopeer2-server fails when connecting to ONOS controller

### ISSUE THREAD

**Issue by yuliya2017** [CESNET/Netopeer2#299]
Hi All, 

I am having troubles with connecting device via Netopeer2-server to ONOS controller.
I have Sysrepod, Sysrepo-plugind and Netopeer2-server running all correctly, when I use Netopeer2-cli i can configure the device no problem. 
I am attempting the same but using ONOS controller instead of Netopeer2-cli. 
When  try to connect to ONOS,  Netopeer2-server just hangs and keeps trying to reestablish the connection and asking for user authentication.
Please find logs attached.
[netopeer-log-on-connect-to-onos.txt](https://github.com/CESNET/Netopeer2/files/2220165/netopeer-log-on-connect-to-onos.txt)
[onos-log-on-connecting-to-netopeer2-server.txt](https://github.com/CESNET/Netopeer2/files/2220166/onos-log-on-connecting-to-netopeer2-server.txt)

I would  be grateful if you can please suggest on where I might have made a mistake or where should I change my configuration. 

Thank you for your help. 
Kind Regards, 
Yuliya

**Comment by michalvasko** [comment]
Hi Yuliya,
I do not think it is a problem of your configuration and would blame the NETCONF client for doing something incorrectly because it is possible to connect to *netopeer2-server* with `ssh(1)`, for example, but also several other clients. We may take a look later but I think you should try to contact the maintainers of the ONOS controller, if possible.

Regards,
Michal

**Comment by michalvasko** [comment]
Hi Yuliya,
we have made the effort and tried it. *netopeer2-server* always fails on `ssh_handle_key_exchange()` which is a function from *libssh*. So, either there is a bug in this function (highly unlikely) or ONOS controller is not correctly establishing SSH session.

Regards,
Michal

**Comment by yuliya2017** [comment]
Hi Michal,

Thanks for your help.
It seems to be a bug in the onos controller side.

Kind Regards,
Yuliya
________________________________

**Comment by yuliya2017** [comment]
Hi Michal, 

We still work on this problem, I have made a few changes such as 
I have done the following in ONOS 1.14
ssh-keygen -t rsa
cat ~/.ssh/id_rsa.pub > cat ~/.ssh/authorized_keys
and then run onos and send json file as usual to onos.

The error I am getting now is different. It looks like netopeer2-server tries to connect, makes 5 attempts and then just segfaults.
Can you please advise on what could be an issue? 
Please find the logs attached.
Thank you kindly for your help.

[netopeer2-server-log-after-pushing-keys.txt](https://github.com/CESNET/Netopeer2/files/2248760/netopeer2-server-log-after-pushing-keys.txt)
[onos-1.14-log-after-pushing-ssh-keys2.txt](https://github.com/CESNET/Netopeer2/files/2248761/onos-1.14-log-after-pushing-ssh-keys2.txt)



Kind Regards, 
Yuliya

**Comment by michalvasko** [comment]
Hi Yuliya,
I see no actual difference and from the output it seems the server crashes at the same place, `ssh_handle_key_exchange()`. So, nothing we can do about it, there is a problem in the client. You could perhaps report this problem to *libssh* because I guess it should not crash no matter what the client sends.

Regards,
Michal

**Comment by yuliya2017** [comment]
Hi Michal,

Thank you, I have also checked and seen that its fails on ssh_handle_key_exchange() but was wondering if I missed anything.
Thank you for your help and suggestion, I will try to contact libssh to see what they think could cause this problem.

Kind Regards,
Yuliya
________________________________
