### ISSUE TITLE
Is it possible to start multiple netopeer2 servers in the same Linux machine?

### ISSUE THREAD

**Issue by lrodrin** [CESNET/Netopeer2#302]
Hi,

I need to run different netopeer2 servers (each server with a different port and ip address) in the same machine. It is possible? Someone has done it and knows how to do?

Thank you,

Laura.

**Comment by michalvasko** [comment]
Hi Laura,
you should not need to do this and it is not possible. You can configure one server with many addresses and ports (look into `netopeer2/server/configuration/README.md`).

Regards,
Michal

**Comment by lrodrin** [comment]
Hi Michal,

Thank you for the information.

Best regards,
Laura

**Comment by lrodrin** [comment]
Hi @michalvasko,

Can you give me an example? I am modifying stock_config.xml but the port is not changed.

Thanks,
L.

**Comment by michalvasko** [comment]
Hi Laura,
after you correctly set up *netopeer2-server* (it prints information about parsing some configuration nodes) all you need to do is change its configuration. The simplest way of doing that is probably using *sysrepocfg*

```
sysrepocfg -d startup -f xml -e vim ietf-netconf-server
```

Just modify the data according to the model and after server restart (it is needed because you modified only `startup` datastore this way, not `running`) it should listen on additional interfaces you specified. You can also accomplish the same thing using an `<edit-config>`.

Regards,
Michal

**Comment by lrodrin** [comment]
Hi Michal,

Thank you so much! Are always very helpful.

Best regards,
L.

**Comment by lrodrin** [comment]
Hi Michal,

Finally it works. Thanks for the support.

Laura.

**Comment by ggangliu** [comment]
Hi, May i still ask this question again ? Is there any changes on this question ? or  where to check netopeer2/server/configuration/README.md file, it seems that there is no server folder now, thanks

**Comment by ggangliu** [comment]
> Please look into the main README.md file (`netopeer2/README`), section Server configuration.

Really thanks
