### ISSUE TITLE
Discuss about xpath filter

### ISSUE THREAD

**Issue by fanchanghu** [CESNET/netopeer2#309]
Hi,
I noticed that netopeer2-server will return the whole subtree for xpath like `/top/users/user[name='fred']`, which may be effected by the example in [RFC 6241](https://tools.ietf.org/html/rfc6241#section-8.9.5). However, it seems that this may not be the true intention of the RFC. I think that only the selected node should be returned for such xpath. 

I'll give my understanding follow, first let's copy the example here:
```
     <rpc message-id="101"
          xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
       <get-config>
         <source>
           <running/>
         </source>
         <!-- get the user named fred -->
         <filter xmlns:t="http://example.com/schema/1.2/config"
                 type="xpath"
                 select="/t:top/t:users/t:user[t:name='fred']"/>
        </get-config>
     </rpc>

     <rpc-reply message-id="101"
                xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
       <data>
         <top xmlns="http://example.com/schema/1.2/config">
           <users>
             <user>
               <name>fred</name>
               <company-info>
                 <id>2</id>
               </company-info>
             </user>
           </users>
         </top>
       </data>
     </rpc-reply>
```
As you see, only `name` and `company-info/id`, which could be treated as identification for the user, are returned by the request. (this kind of identification could not be described as list key with YANG.)

And in the other part of the RFC, the whole `user` node should be like this:
```
             <user>
               <name>fred</name>
               <type>admin</type>
               <full-name>Fred Flintstone</full-name>
               <company-info>
                 <dept>2</dept>
                 <id>2</id>
               </company-info>
             </user>
```

RFC original text for this:
```
   o  If any sibling or ancestor nodes of the result node are needed to
      identify a particular instance within a conceptual data structure,
      then these nodes MUST also be encoded in the response.
```
If the selected node is something like list in YANG, only the list key which is used to identify a particular instance should be returned. If the client want to get the whole subtree, xpath like `/top/users/user[name='fred']//.` should be used.

So, for netopeer2-server, we don't need to append `//.` to the given xpath, just use the given xpath is ok.

**Comment by michalvasko** [comment]
Hi,
I have already changed this behaviour a few times so there was some confusion. You may be right but the current implementation is mostly referring to [this section, last paragraph](https://tools.ietf.org/html/rfc6241#section-8.9.1). **Subtrees** are mentioned, not nodes.

Regarding the example, it is probably wrong no matter how we interpret the XPath filter. Why was only `company info` with `id` included? It does not identify a particular instance of `user`.

So, unless you can provide more arguments I am keeping it the way it is. I agree that it is confusing but I think the intention was to unify subtree and XPath filter so that both select subtrees.

Regards,
Michal

**Comment by fanchanghu** [comment]
Hi,
I have no more arguments for this , the RFC does not describe it clearly enough.

However, if you decide to keep current implementation, just appending `//.` seems not enough for all situation, such as `/top/users/user[name='fred']|/top/users/user[name='xxx']` only gets the subtree for user `xxx`.

**Comment by michalvasko** [comment]
Hi,
you are right, of course. However, using unions in these XPath filters is kind of useless mainly because *sysrepo* will not return data from 2 modules anyway. Your example can be simply rewritten into `/top/users/user[name='fred' or name='xxx']` and it will work fine. So, I will just mention this in known issues and keep it the way it is for now, sorry. I do not think it is worth it to make sure all the possible XPaths would work perfectly, it would not be simple.

Regards,
Michal
