### ISSUE TITLE
YANG model not shown in capabilities

### ISSUE THREAD

**Issue by mislavn** [CESNET/Netopeer2#335]
If the YANG model contains `yang-version 1.1;` the YANG model will be properly handled, it will be displayed in `sysrepoctl -l` but it will not be shown in NETCONF capabilitise.

```
root@1d80c1d3d8bd:/# netopeer2-server -V
netopeer2-server 0.6.10
compile time: Aug 24 2018, 11:01:43
root@1d80c1d3d8bd:/# sysrepod -v
sysrepod - sysrepo daemon, version 0.7.4
```

**Comment by alangefe** [comment]
Hi Mislav,

I think this is expected behavior for YANG 1.1 models. You can find these models in the `/modules-state/module` list in `ietf-yang-library` instead.

RFC 7950 (YANG 1.1) changed the way the server announces the modules it supports. (See [section 5.6.4](https://tools.ietf.org/html/rfc7950#section-5.6.4).) Instead of presenting modules in the capabilities list as in RFC 6020, the new specification indicated that they are to be presented via `ietf-yang-library`.

This change was implemented in https://github.com/CESNET/libnetconf2/issues/59 and https://github.com/CESNET/libnetconf2/commit/24a1841.

Regards,
Andrew

**Comment by michalvasko** [comment]
Hi Mislav,
@alangefe said it all so I am just conforming it.

Regards,
Michal

**Comment by mislavn** [comment]
Thanks, closing the ticket.
