### ISSUE TITLE
Dummy auth backend for prototyping (privilege separation)

### ISSUE THREAD

**Issue by jktjkt** [CESNET/Netopeer2#34]
I'm prototyping an application which uses `sysrepo`, and using `netopeer2-server` as a NETCONF interface along with its client for actual modifications sounds like an obvious choice. However, the server cannot be used in an privilege-separated environment without affecting the rest of the system.
- The systemwide SSH host key is being read. That might be convenient, but SSH handles spearate host keys just fine. This can be easily hacked around by modifying the `config.h.in`.
- `libnetconf2` (should I file a bug in there, or is it just a matter of configuring it from the app, ie., netopeer2?) uses the C library functions for retrieving of user account information, including an attempt to read the shadow entries for password access. I would expect that a real-world production deployment would use PAM (if working on a full Linux and not on embedded) to allow for stuff like LDAP. On the other hand, for manual testing it would be nice to have some dummy auth backend with plaintext usernames/password. I'll see if I can fake this with some `LD_PRELOAD` trickery after the weekend.

(Please feel free to tell me to use another method for contacting you. I'm also at CESNET after all. However, as this is a FLOSS project I'm going through the default FLOSS route for now.)

**Comment by michalvasko** [comment]
Hi,
in the same order,
- You said it, just change `config.h.in` to whatever path you want. In near future we should finally be able to implement basic NETCONF server configuration, which includes setting the host key.
- For testing purposes I always found using public key authentication best. We use locally configured users because it is simple and it is basically how `ietf-system` `local-users` authentication ([RFC7317](https://tools.ietf.org/html/rfc7317#section-3.5.2)) works. Once we fully implement it we can make it independent of actual system user configuration and use only NETCONF configuration. To utilize PAM I believe one should augment `ietf-system` with a custom module that will define all the necessary configuration nodes (or at least add a new identity that would mean user authentication using PAM).

Contacting us using this issue tracker is fine.

Regards,
Michal
