### ISSUE TITLE
Subscribe on subscription has no effect.

### ISSUE THREAD

**Issue by wmakuch** [CESNET/Netopeer2#375]
Hello Michal!

I need to know by sysrepo if rpc <create-subscription> has been sent from cli.
Calling function _sr_rpc_subscribe_ with parameter _/notifications:create-subscription_ returns SR_ERR_OK.
Althought rpc is send from cli, callback _rpc_cb_ is never called.
I met with the same problem, trying subscribe on rpc <get> - _/ietf-netconf:get_.
Is is expected result? If yes - please tell me, how can I avoid it and successfully subscribe on those rpcs.

Best Regards,
Wojciech Makuch

**Comment by michalvasko** [comment]
Hi Wojciech,
yes, it actually is expected because these RPCs (`notifications:create-subscription` and all RPCs from `ietf-netconf`) are implemented directly in *netopeer2-server* so when such a request comes from a NETCONF client, it is not passed to *sysrepo*.

I do not know what exactly are you trying to do so it is hard to suggest solutions. If you want to perform some additional RPC-specific work, you can add this code into each RPC callback in *netopeer2-server* (they are assigned in `main.c:server_init()` so you can find the exact function names there).

Regards,
Michal

**Comment by wmakuch** [comment]
Hi,
This solved my problem!
In the case of `notifications:create-subscription`, callback `op_generic` is not called and none of sysrepo's functions handle this RPC. I added op_generic logic into `op_ntf_subscribe` and got expected result.

Best Regards,
Wojciech Makuch
