### ISSUE TITLE
SSH channel poll error (Socket error: disconnected) in netopeer2-server log

### ISSUE THREAD

**Issue by shishirpandey29** [CESNET/Netopeer2#391]
Hello,

I am observing  call home connecting and disconnecting in netopeer2-server log .

```
 
Jan  5 02:15:42 mavdu netopeer2-server[7350]: Call Home client "test_ssh_ch_client" session terminated, reconnecting...
Jan  5 05:16:08 mavdu netopeer2-server[17267]: Call Home client "test_ssh_ch_client" session terminated, reconnecting...
Jan  8 01:46:36 mavdu netopeer2-server[4032]: Call Home client "test_ssh_ch_client" session terminated, reconnecting...
Jan  8 02:40:00 mavdu netopeer2-server[13137]: Call Home client "test_ssh_ch_client" session terminated, reconnecting...
Jan  8 02:47:22 mavdu netopeer2-server[13137]: Call Home client "test_ssh_ch_client" session terminated, reconnecting...
Jan  8 05:18:28 mavdu netopeer2-server[18618]: Call Home client "test_ssh_ch_client" session terminated, reconnecting...
Jan  8 05:18:29 mavdu netopeer2-server[18618]: Call Home client "test_ssh_ch_client" session terminated, reconnecting...
Jan  8 07:33:13 mavdu netopeer2-server[17230]: Call Home client "test_ssh_ch_client" session terminated, reconnecting...
Jan  8 07:39:02 mavdu netopeer2-server[6580]: Call Home client "test_ssh_ch_client" session terminated, reconnecting...
Jan  8 07:41:36 mavdu netopeer2-server[8292]: Call Home client "test_ssh_ch_client" session terminated, reconnecting...
Jan  8 12:42:43 mavdu netopeer2-server[9788]: Call Home client "test_ssh_ch_client" session terminated, reconnecting...
Jan  8 15:52:18 mavdu netopeer2-server[8066]: Call Home client "test_ssh_ch_client" session terminated, reconnecting...
``` 
Before call home disconnect , I  always observe error " SSH channel poll error (Socket error: disconnected)."
```
 Jan  2 13:40:52 mavdu netopeer2-server[4170]: Session 10: SSH channel poll error (Socket error: disconnected).
Jan  2 13:40:52 mavdu netopeer2-server[4170]: Session 10: thread 3 event session terminated.
Jan  2 13:40:52 mavdu netopeer2-server[4170]: (sr_event_notif_send:3712) Error by processing of the request.
Jan  2 13:40:52 mavdu netopeer2-server[4170]: np2srv_sr_event_notif_send failed (sysrepo: Validation of the changes failed).
Jan  2 13:40:52 mavdu netopeer2-server[4170]: Call Home client "test_ssh_ch_client" session terminated, reconnecting...
```

could you please check,

**Comment by michalvasko** [comment]
Hi,
could you please provide the client output, also what client are you using? Is this all that the server prints? If so, then everything seems correct, the client suddenly disconnects so the server reconnects.

Regards,
Michal

**Comment by yahovevo** [comment]
Hi Michal,

I've attached netconf server log at that time. 
I think abnormal closed client makes netopeer2 server shut down. but I can't find root cause.

=============> full
[1970/01/01 00:02:19.457616, 1] ssh_socket_exception_callback:  Socket exception callback: 1 (0)
[1970/01/01 00:02:19.457816, 1] ssh_socket_exception_callback:  Socket error: disconnected
ERROR: Session 3: SSH channel poll error (Socket error: disconnected).
VERBOSE: Session 3: thread 1 event session terminated.
DEBUG: Sending unsubscribe request.
ERROR: Session 4: SSH channel poll error (Socket error: disconnected).
VERBOSE: Session 4: thread 0 event session terminated.
DEBUG: Sending event-notification request.
DEBUG: unsubscribe request sent, waiting for response.
DEBUG: unsubscribe response received, processing.
DEBUG: Sending unsubscribe request.
DEBUG: unsubscribe request sent, waiting for response.
VERBOSE: Call Home client "test_ssh_ch_client" session terminated, reconnecting...
VERBOSE: nc_sock_connect(10.1.42.31, 4334, 5, -1)
VERBOSE: Trying to connect via IPv4.
VERBOSE: Successfully connected to 10.1.42.31:4334 over IPv4.
DEBUG: unsubscribe response received, processing.
DEBUG: Sending unsubscribe request.
DEBUG: unsubscribe request sent, waiting for response.
udhcpc: sending discover
DEBUG: unsubscribe response received, processing.
DEBUG: Sending unsubscribe request.
DEBUG: unsubscribe request sent, waiting for response.
VERBOSE: Received an SSH message "request-service" of subtype "ssh-userauth".
VERBOSE: Received an SSH message "request-auth" of subtype "none".
DEBUG: unsubscribe response received, processing.
DEBUG: Sending unsubscribe request.
DEBUG: unsubscribe request sent, waiting for response.
VERBOSE: Received an SSH message "request-auth" of subtype "password".
VERBOSE: User "rcncuser" authenticated.
VERBOSE: Received an SSH message "request-channel-open" of subtype "session".
VERBOSE: Received an SSH message "request-channel" of subtype "subsystem".
VERBOSE: Call Home client "test_ssh_ch_client" session 5 established.
DEBUG: unsubscribe response received, processing.
DEBUG: Sending unsubscribe request.
DEBUG: unsubscribe request sent, waiting for response.
DEBUG: unsubscribe response received, processing.
DEBUG: Sending unsubscribe request.
DEBUG: unsubscribe request sent, waiting for response.
DEBUG: unsubscribe response received, processing.
DEBUG: Sending unsubscribe request.
DEBUG: unsubscribe request sent, waiting for response.
DEBUG: unsubscribe response received, processing.
DEBUG: Sending unsubscribe request.
DEBUG: unsubscribe request sent, waiting for response.
DEBUG: unsubscribe response received, processing.
DEBUG: Sending unsubscribe request.
DEBUG: unsubscribe request sent, waiting for response.
DEBUG: unsubscribe response received, processing.
DEBUG: Sending unsubscribe request.
DEBUG: unsubscribe request sent, waiting for response.
DEBUG: unsubscribe response received, processing.
DEBUG: Sending event-notification request.
DEBUG: event-notification request sent, waiting for response.
[cpri_ori/sysrepo_thread.cpp#,2532]
values_cnt=4
xpath: /ietf-netconf-notifications:netconf-session-end/username
xpath: /ietf-netconf-notifications:netconf-session-end/session-id
xpath: /ietf-netconf-notifications:netconf-session-end/source-host
xpath: /ietf-netconf-notifications:netconf-session-end/termination-reason
name=rcncuser, id=3, ip=10.1.42.31, reason=other
DEBUG: event-notification response received, processing.
VERBOSE: Generated new event (netconf-session-end).
DEBUG: Sending session-stop request.
DEBUG: session-stop request sent, waiting for response.
DEBUG: session-stop response received, processing.
DEBUG: event-notification request sent, waiting for response.
[cpri_ori/sysrepo_thread.cpp#,2532]
values_cnt=4
xpath: /ietf-netconf-notifications:netconf-session-end/username
xpath: /ietf-netconf-notifications:netconf-session-end/session-id
xpath: /ietf-netconf-notifications:netconf-session-end/source-host
xpath: /ietf-netconf-notifications:netconf-session-end/termination-reason
name=rcncuser, id=4, ip=10.1.42.31, reason=other
DEBUG: event-notification response received, processing.
VERBOSE: Generated new event (netconf-session-end).

=============> summary
ERROR: Session 3: SSH channel poll error (Socket error: disconnected).
xpath: /ietf-netconf-notifications:netconf-session-end/termination-reason
name=rcncuser, id=3, ip=10.1.42.31, reason=other


======> code
worker_thread()
  nc_ps_poll()
    ret = nc_ps_poll_session_io(cur_session, NC_SESSION_LOCK_TIMEOUT, ts_cur.tv_sec, msg);  //libnetconf2/session_server.c
      r = nc_session_io_lock(session, io_timeout, __func__); 
      case NC_TI_LIBSSH:
      r = ssh_channel_poll_timeout(session->ti.libssh.channel, 0, 0);
          rc = ssh_handle_packets_termination(channel->session, timeout,ssh_channel_read_termination, &ctx);
      else if (r == SSH_ERROR) {
        sprintf(msg, "SSH channel poll error (%s)", ssh_get_error(session->ti.libssh.session));
        //ERROR: Session 5: SSH channel poll error (Socket error: disconnected).
        session->status = NC_STATUS_INVALID;
        session->term_reason = NC_SESSION_TERM_OTHER;

After that, netopeer2-server is killed by SSH channel poll error.
Could you check this situation?

Regards
Boyong

**Comment by michalvasko** [comment]
Hi Boyong,
I still do not fully understand. The channel poll error is not such a big problem, the client simply did not close the session properly. But after that *netopeer2* continues in the correct way meaning it tries to reconnect the Call Home session. And what do you mean by "makes netopeer2 shut down"? Is the whole process terminated? I do not see any output indicating that but if it is, then please provide the full output up to that point (`netopeer2-server -v2` is fine, no need for debug output yet).

Regards,
Michal

**Comment by yahovevo** [comment]
[190205_np2_terminate_alllog.log](https://github.com/CESNET/Netopeer2/files/2862870/190205_np2_terminate_alllog.log)

I've attached log you can investigate np2 process is killed suddenly. Please check log.
If you need some debug option, I can reproduce this on our environment.

Regards,
Boyong

**Comment by michalvasko** [comment]
Hi Boyong,
firstly, you are using an older version of *netopeer2-server*, so please update all the libraries, not that long ago there were some enhancements to Call Home in *libnetconf2* done, so maybe you do not have those and they can help. Other than that, I do not know why would the server shut down because I cannot find any reason for it in the log. Then again, you may be using such an old version that the reason for its termination was fixed.

Regards,
Michal

**Comment by shishirpandey29** [comment]
Hi,
I did not observe issue again.
it seems  some network issue that caused socket disconnection.
