### ISSUE TITLE
How to set value for elements marked "Config false"

### ISSUE THREAD

**Issue by qynum123** [CESNET/Netopeer2#404]
Hi,
I want to import some data for testing only,  for example:
sysrepocfg --import=mytest.xml --format=xml --datastore=startup myTestModule
As some elements are defined as "config false" in the module file, so the import was failed.
Could you please help me how should I do for this? Thanks in advance.

**Comment by michalvasko** [comment]
Hi,
for the import you should be able to use `-n` (`--not-strict`) *sysrepocfg* option.

Regards,
Michal

**Comment by qynum123** [comment]
Great, thanks very much!

**Comment by qynum123** [comment]
Hi, 
-n, --not-strict   Flag used to silently ignore unknown data from any supplied data file.
This will ignore the configuration for the elements marked with "config false", but I just want to set the values for these elements.
If I can't imported the data as this, is there any other way I can set the values for these elements? 
Thanks.

**Comment by michalvasko** [comment]
Hi,
in that case look [here](http://www.sysrepo.org/static/doc/html/subscribtions.html#data_providers).

Regards,
Michal

**Comment by qynum123** [comment]
Thanks, so for supporting that, we should write a new plugin or service base on sysrepo, do netopeer2 also provide similar framework or add source codes in some places to extend the functionalities?

**Comment by michalvasko** [comment]
Hi,
if you mean adding some *sysrepo* plugins directly into *netopeer2* then no, this is not supported (and I do not think it even should be).

Regards,
Michal

**Comment by qynum123** [comment]
I mean how to extend the netopeer2 functionalities to support customize the user defined model.
After took a look at the netopeer2 source, it seems we can add some like the following(take ietf-netconf-monitoring as an example):
rc = sr_dp_get_items_subscribe(np2srv.sr_sess.srs, "/ietf-netconf-monitoring:netconf-state", np2srv_state_data_clb, NULL, SR_SUBSCR_CTX_REUSE, &np2srv.sr_subscr);
provide the data in the callback function, right?

**Comment by michalvasko** [comment]
Well, yes, you can modify *netopeer2-server* code as you see fit. My point was that this should not be done, why do you want to add your custom model state data callback directly into *netopeer2-server*? It has callbacks for `ietf-netconf-monitoring` and `ietf-netconf-server` (and one for `ietf-system` because of `ietf-netconf-server`), which are NETCONF-specific models.

To support other models you should follow the general *sysrepo* principles (it actually has nothing to do with *netopeer2-server*) meaning either write your own daemon that will provide these data or use *sysrepo-plugind* and write just a plugin for this purpose.

Regards,
Michal

**Comment by qynum123** [comment]
Got it, thanks very much for your reply!
