### ISSUE TITLE
Launching multiple instances of netopeer2-server

### ISSUE THREAD

**Issue by ManjeshHS** [CESNET/netopeer2#416]
Hi,

I need to launch multiple instances of netopeer2-server on the same machine with these conditions:
> all of them must have unique pid
> all of them must listen on unique ip-address (port can be the same)
> all of them must support both ssh and tls requests 
> all of them use the same sysrepo db and manage their corresponding data

Is this possible ?
If yes, please let me know the procedure to achieve it (like the changes to done into installation, configuration, yang modules, etc.).

Thanks in advance.

**Comment by michalvasko** [comment]
Hi,
*netopeer2-server* is (mostly artificially) limited to one instance per system so it is not possible. You can try to remove this limit (checking that PID file already exists) but it will most likely not work because I believe *libnetconf2* itself has this limit. We thought there is no reason to support this, why would you want to do this?

Regards,
Michal

**Comment by ManjeshHS** [comment]
Hi,
Thanks for the reply.
I need to launch multiple instances of netopeer2-server in my system which interfaces with multiple network entities (aggregation). I need each network entity to be served by separate instance of netopeer2-server.

**Comment by jktjkt** [comment]
Why do you need each network interface served by a different NETCONF server instance? I am confused because you also say you want to publish the same instance of the data store via all these NETCONF servers.

**Comment by michalvasko** [comment]
Hi,
I see, good to know there is a use-case. However, like I said, *netopeer2-server* with the current *sysrepo* will not support this, it would be too much work. Also, I am not even sure how it would work in theory because *sysrepo* **will** have to be the same (it is even your requirement) and *netopeer2* uses it for storing its configuration, so it could not be different. Lastly, even `ietf-netconf-server` YANG module does not support several server instances, so it could not be used if this was supported.

Regards,
Michal

**Comment by ManjeshHS** [comment]
Hi,
There is no strict requirement that all such netopeer2-server instances must use the same sysrepo db.
If all of them use their own instance of sysrepo db, then is this possible ?
Please share your comments.

**Comment by jktjkt** [comment]
Hi ManjeshHS, I still do not understand what your use case really is. Why do you want to have standalone processes per IP address? What is the motivation behind this? What end goal do you want to achieve?

**Comment by kobi-ca** [comment]
Folks, let me shed some light on the question since it is a good one and the use case actually exists in the industry.
Think about on multiple processes each is a different Network Function that does one specific thing for the overall architecture.
Now, it needs its own NC server, with its own DB so if we need to migrate it to a different node (we == K8s) it will take the POD (which has the NC server and the NF) and migrate it as a single atomic unit.

My understanding for the above thread (2019 - anything changed since?) that it is not possible.
I can see that SR DB is using shared memory. So there is one /dev/shm/sr_* in the system which is a very limiting factor.
Is my understanding correct?

**Comment by jktjkt** [comment]
> My understanding for the above thread (2019 - anything changed since?) that it is not possible. I can see that SR DB is using shared memory. So there is one /dev/shm/sr_* in the system which is a very limiting factor. Is my understanding correct?

- Aren't Kubernetes containers using separate `/dev/shm` mountpoints for individual containers/pods, though?
- if you really need to, there's a simple env variable for prefixing the files below a single SHM prefix (that's very handy for CI, parallel testing, etc).

Anyway, I suggest opening a new issue instead of commenting on a 3+ year old one, and describing what exactly you have in mind.

**Comment by kobi-ca** [comment]
> * Aren't Kubernetes containers using separate `/dev/shm` mountpoints for individual containers/pods, though?

Not sure I understand. If NP2 lives in a container, I need to use the `--ipc` to be able to communicate with the external "world".

> * if you really need to, there's a simple env variable for prefixing the files below a single SHM prefix (that's very handy for CI, parallel testing, etc).

Thanks for the tip. I'll take a look. I found this: https://github.com/sysrepo/sysrepo/issues/2784, which has `SYSREPO_SHM_PREFIX`

BTW, I did not want to create a new issue simply because there is a lot of good context here and my comment is very relevant to the entire thread.
