### ISSUE TITLE
Subcribe notifications with special xpath filter cause segment fault

### ISSUE THREAD

**Issue by yangtian127** [CESNET/Netopeer2#432]
hi

On netopeer2-cli, subscribing notififaction with following xpath filter will cause segment fault and core dump
subscribe --filter-xpath /ietf-netconf-notifications:netconf-config-change/edit[target="if:interfaces/interface"]

netopper2 (v0.7-r1)
libyang (v0.16-r2)
libnetconf2 (v0.12-r1)
sysrepo (v0.7.7)

**Comment by michalvasko** [comment]
Hi,
when I tried it with the latest `devel` (of all the projects), it did not crash, just failed with an error. But, to fix this, you probably just need to use `ietf-interfaces` instead of `if` as the module prefix (we use JSON-style prefixes so that it is not required to bother with XML namespaces).

Regards,
Michal

**Comment by yangtian127** [comment]
Hi, michal
coredump detect crash at free() in lydict_remove()
Maybe this issue has been resolved in commit [
ea726ca](https://github.com/CESNET/libyang/commit/ea726ca5ed4f54da24806955758f8b15d4078245) tp resolve #779
