### ISSUE TITLE
[devel-server] netopeer2-server print "nc_ps_poll: failed to wait for a pollsession condition ..."

### ISSUE THREAD

**Issue by brchiu** [CESNET/Netopeer2#465]
When run new netopeer2-server on petalinux on xilinx's QEMU, it keeps print  `nc_ps_poll: failed to wait for a pollsession condition ...`,  so I add debug information by changing line 901 of session_server.c as : 

```
ERR("%s: failed to wait for a pollsession condition (%s) thread %x id %d head %d begin %d queue_len %d.", func, strerror(ret), pthread_self(), *id, ps->queue[ps->queue_begin], ps->queue_begin, ps->queue_len);
```
then I get the following [log](https://gist.github.com/brchiu/ad28dea3283f3e7d39031006a7256aae)

```
[ERR]: LN: nc_ps_poll: failed to wait for a pollsession condition (Connection timed out) thread ae3201b0 id 1 head 0 begin 0 queue_len 5.
[ERR]: LN: nc_ps_poll: failed to wait for a pollsession condition (Connection timed out) thread b0086540 id 2 head 0 begin 0 queue_len 4.
[ERR]: LN: nc_ps_poll: failed to wait for a pollsession condition (Connection timed out) thread adb1f1b0 id 3 head 0 begin 0 queue_len 3.
[ERR]: LN: nc_ps_poll: failed to wait for a pollsession condition (Connection timed out) thread ad31e1b0 id 4 head 0 begin 0 queue_len 2.
[ERR]: LN: nc_ps_poll: failed to wait for a pollsession condition (Connection timed out) thread ae3201b0 id 1 head 0 begin 0 queue_len 5.
[ERR]: LN: nc_ps_poll: failed to wait for a pollsession condition (Connection timed out) thread b0086540 id 2 head 0 begin 0 queue_len 4.
```
Looks like the first item of `nc poll session` queue was not cleared for some reason.

By the way, this phenomenon can not be reproduced on Ubuntu. 

I doubt low process speed of QEMU environment would uncover some problems, e.g. race condition, which are reproducible in more powerful Ubuntu environment.

**Comment by michalvasko** [comment]
Hi,
please pull latest *libnetconf2* and then start the server with `-c MSG` (instead of `-v`). There will be **a lot** of output generated fast, but just attach it in a text file here, please. I suspect it will be a problem with system thread scheduler (thread aging), but we will see.

Regards,
Michal

**Comment by brchiu** [comment]
Due to too lengthy log output, only [partial log at end] available. (https://gist.github.com/brchiu/5f4bf357be7a72398002183e65d7549d)

**Comment by brchiu** [comment]
I figured out how to set unlimited lines of terminal, FYI. [full log](https://gist.github.com/brchiu/ecd9146c8d96586ebc1b9f360c85fe62)

**Comment by michalvasko** [comment]
Hi,
I found nothing suspicious in the logs so it seems it regularly timed out. Why it then cannot recover I am not positive but it simply seems that the blocking thread is being starved by all other threads continually trying to get the lock. I would appreciate if you could use a debugger and once it starts to fail, break the execution and print the backtrace of all the threads. There may be some interesting information.

Other than that, you can update to the latest version and I think you will no longer get the errors. I have simply increased the timeout because 1 s really may not be enough for slower systems. Also, if you reduce the number of threads (`-DTHREAD_COUNT=5` is the default), there should be less contention.

Regards,
Michal

**Comment by brchiu** [comment]
With original version, i.e. before increasing NC_PS_QUEUE_TIMEOUT : 
I use gdb to run netopeer2-server and break when these messages printed, FYI [gdb thread info](https://gist.github.com/brchiu/6b3849d81063e5b873b756dfcd0caf48). Due to limitation of embedded system program space, I am not able to build them with debug info enabled. So we can only "guess" where these threads wait at.

I will also try increasing this value and/or decrease thread count. However, as I already tried on old version sysrepo/netopeer2 (master), I will encounter this message or, even worse, hang without response to key press input if I install more oran yang modules.

Anyway, I will test again.

**Comment by brchiu** [comment]
After increase [gdb log after increase NC_PS_QUEUE_TIMEOUT to 5000](https://gist.github.com/brchiu/58f8c1c184377af0c102c8ada3026fc2)

**Comment by michalvasko** [comment]
Hi,
I still could not find anything wrong in the log. With increased timeout the processing even resumes normal operation once the blocking thread finishes its work. Why it needs tens of seconds for that (you can tell how long it actually takes) I am unsure but it is possible with really complex models and slow HW.

As for some fix, I am not sure what would be appropriate. You should definitely decrease thread count. If you are fine with limited concurrency you could use a single thread and then should have no timeout problems. If you want more threads then you will get these errors but they should not matter and the server should continue to work.

I have increased sleep time for the server threads so that should make things better for your case. I do not think I can do more.

Regards,
Michal
