### ISSUE TITLE
Configuration for Call-Home ssh password authentication

### ISSUE THREAD

**Issue by manas42** [CESNET/Netopeer2#488]
Hi,

https://github.com/CESNET/Netopeer2/blob/master/server/configuration/README.md
In the Configuration README page, it is stated that:

> In all the SSH examples you used either `password` or `interactive` authentication. It is also possible to use `publickey` authentication, but it needs to be configured.

I wish to use password authentication for Call Home, but I'm not sure if the configuration for the password is the `cleartext-password` node in module `ietf-keystore`? 

If so, according to the README page, the configuration is listed in **Non-implemented Configuration** section. So even if I use <edit-config> to create a password, it would not be used by `netopeer-server`?

**Comment by michalvasko** [comment]
Hi,
all SSH authentication methods are shared for both standard sessions and Call Home so you do not need to configure anything to use `password` method for Call Home. The system users/passwords will be used.

Regards,
Michal

**Comment by manas42** [comment]
Hi,

Yes, I know the system user/password would be used, but I wish to use a specific set of user/password for the server in Call Home. Is it possible?

**Comment by manas42** [comment]
Specifically, this feature is used for NACM. The server would use a default username/password to Call-Home the "admin" client, and other clients could use different usernames/passwords to connect to the server. The users would be in different privilege groups.

**Comment by michalvasko** [comment]
Hi,
the reason is not that important. The problem is that *libnetconf2* really does not distinguish between standard and Call Home SSH authentication so the same mechanisms must be used. But there are some other options you can try.

There is an authentication callback that can be set but will be used for all sessions. However, you can determine what kind of session are you authenticating (`nc_session_is_callhome()`) so I think the only problem with this method is that you would have to authenticate standard sessions yourself. You could use the functions in *libnetconf2* but they are not part of API.

Actually, I am not sure how else to do this, you can simply create a system user with the desired credentials and then it can be used in Call Home, if that is not a problem.

It would probably be quite simple to add this feature to the new *netopeer2* that works with the new *sysrepo* because there all this configuration works quite differently.

Regards,
Michal

**Comment by manas42** [comment]
Thank you.

I did not make it clear. It is OK if Call Home and standard SSH use the same credentials. My question should be whether I could configure standalone usernames/passwords on NETCONF server without creating system users, since it would be some extra work on our embedded system at the moment. 

Looking through the code, if I were to modify the netopeer2-server code to implement a standalone credential feature, I could simply use `nc_server_ssh_set_passwd_auth_clb`  and lookup the password for a specific username in the callback, whether according to the mapping in `ietf-keystore` or in a simple dict. Am I right?

**Comment by michalvasko** [comment]
Hi,
if it is fine that system users will not be used at all then just set that callback and you can authorize whatever users you want, like you said.

Regards,
Michal

**Comment by manas42** [comment]
Appreciate the help
