### ISSUE TITLE
Netopeer-server with TLS

### ISSUE THREAD

**Issue by masif-cs** [CESNET/netopeer2#491]
Hi,
We want to use NETCONF with TLS.
For this we have compiled libnetconf with TLS enabled and SSH disabled.
1. Now when we run netconf-server, it is giving following error:
 netopeer2-server -d -v 2
netopeer2-server: symbol lookup error: netopeer2-server: undefined symbol: nc_libssh_thread_verbosity

2. So we tried to comment out the  nc_libssh_thread_verbosity from main.c and tried to do cmake ..

3. but now it is giving following error:
CMake Error at CMakeLists.txt:119 (message):
  Missing SSH support in libnetconf2, server requires SSH to be supported.
-- Configuring incomplete, errors occurred!

Can you please help us how to compile netopeer for TLS enabled.

Thanks!
Asif

**Comment by michalvasko** [comment]
Hi Asif,
SSH support is mandatory for the server (NETCONF requirement), so just compile *libnetconf2* with the support for both SSH and TLS and you should be fine. You can disable all SSH interfaces so the server will actually not listen for SSH connections.

Regards,
Michal

**Comment by masif-cs** [comment]
Hi,

When I tried compiling libnetconf2 with SSH & TLS on. It got compiled successfully and installed too. But when I am trying to compile Netopeer2, I am getting below errors:

cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
-- Unable to learn libnetconf2 thread support, check skipped
-- Could NOT find CURL (missing:  CURL_LIBRARY CURL_INCLUDE_DIR) 
-- libcurl not found, url capability will not be supported
-- Configuring done
-- Generating done
-- Build files have been written to: /home/airvana/masif/netconf/Netopeer2/server/build

Can you please tell me what is the issue?

**Comment by michalvasko** [comment]
Hi,
what exact *sysrepo* version do you have installed? Please `pull` it again if it is not the latest one.

Regards,
Michal

**Comment by masif-cs** [comment]
Hi,

Thanks for the prompt reply. Currently I using all devel version of Netopeer2, sysrepo and libnetconf. With the above option of sr_clean I am able to compile and run it successfully. But netopeer2-server is still listening on SSH instead of TLS. How can I change it to listen on TLS?

Server Log:
[INF]: LN: Listening on 0.0.0.0:830 for SSH connections.

[INF]: LN: Accepted a connection on 0.0.0.0:830.
[INF]: SR: Session 6 (user "root") created.
[2019/11/19 15:11:34.430331, 2] ssh_pki_import_privkey_base64:  Trying to decode privkey passphrase=false
[2019/11/19 15:11:34.432835, 2] ssh_server_connection_callback:  SSH client banner: 
[2019/11/19 15:11:34.432858, 1] ssh_analyze_banner:  Protocol mismatch: 
[2019/11/19 15:11:34.432871, 1] ssh_server_connection_callback:  No version of SSH protocol usable (banner: )
[2019/11/19 15:11:34.432913, 1] ssh_socket_exception_callback:  Socket exception callback: 2 (2)
[2019/11/19 15:11:34.432935, 1] ssh_socket_exception_callback:  Socket error: No such file or directory
[ERR]: LN: SSH key exchange error (Socket error: No such file or directory).

Client Log:
get_default_CRL_dir: Default CRL dir does not exist, creating it.
nc ERROR: SSL_connect failed (Success).
cmd_connect: Connecting to the 0.0.0.0:830 failed.

Could you please help?

**Comment by michalvasko** [comment]
Hi,
mainly, do not connect to the SSH interface. Otherwise, simply change *ietf-netconf-server* configuration. All of this software is meant to do exactly this, manage configuration, so do it :)

Anyway, the simplest way is just to use
```
sysrepocfg --edit=vim -m ietf-netconf-server
```
There you should remove the default SSH listen endpoint and add your TLS listen endpoint. An example of a [specific configuration](https://github.com/CESNET/Netopeer2/blob/devel-server/server/example_configuration/tls_listen.xml) can be found in the repository. As you will see, configuring TLS is not that simple, compared to SSH at least. Reasons are 2. Firstly, you must explicitly configure the authentication, nothing is read from the system. Secondly, there much more authentication artifacts, namely the certificates. To help you understand what each configuration node means, just look into the appropriate [models](https://github.com/CESNET/Netopeer2/blob/devel-server/modules).

Regards,
Michal

**Comment by masif-cs** [comment]
Hi,

Certificate leaf has leafref to certificates, which is not present in ietf-keystore yang model present in Netopeer2 devel branch. Can you please tell me if I missing something?

leaf certificate {
         type leafref {
           path "/ks:keystore/ks:asymmetric-keys/ks:asymmetric-key[ks:"
                + "name = current()/../asymmetric-key]/ks:**certificates**"
                + "/ks:certificate/ks:name";
         }

**Comment by michalvasko** [comment]
Hi,
actually, it is there, but taken from a `grouping` in `ietf-crypto-types`. These are not modules with simple hierarchy, you should use `yanglint`, load all the modules and then print the ones you are interested in with `print --tree <module-name>`. That way you will see all the actual nodes and types in a sensible fashion.

Regards,
Michal

**Comment by meghna-doshi** [comment]
Hi Michal,
Thanks, we were able to run in TLS by setting the desired attributes in ietf-netconf-server yang.
So we basically used sysrepocfg to set the values in ietf-netconf-server.

We have some queries here and need some help here.
1. Our s/w would be packaged as an image and deployed, so there we cannot run sysrepocfg to configure the netopeer. The TLS or SSH configuration would be fixed for a deployment.
2. If we dont use sysrepocfg, where are the xml files which are getting modified for the TLS setting, so that we can directly write values there.
3. We also want to know, like this TLS/SSH configuration, what all default configurations are set in netopeer? Where are the relevant configuration xml files present.

Thanks,
Meghna

**Comment by michalvasko** [comment]
Hi,

2. You cannot directly modify any XML files because there are none. I would strongly recommend using a post-install script for any deployment. But you have many options what to do in this post-install script, easiest is probably to just run `sysrepocfg` and set the desired configuration.

    Now, if you absolutely insist on having a package with everything inside without any scripts, it is theoretically possible. You would have to know the path of *sysrepo* repository (how would you learn that?) and the startup data for all modules are in there, in *libyang* LYB binary format. So, you could take your data, print them into LYB (using `yanglint`, for instance), and then replace `<sysrepo-repository>/data/ietf-netconf-server.startup` with them.

    However, you cannot really install *netopeer2* without a post-install script (which installs required modules among other things) so I do not really see the point. Again, you could hack your way around this, too, but I think it is more trouble than it is worth.

3. Default configuration is set using `sysrepocfg` just like you did in a script that is executed for `make install`. This particular script is [merge_config.sh](https://github.com/CESNET/Netopeer2/blob/devel-server/server/merge_config.sh).

Also, I want to mention that I have used the modules (`ietf-netconf-server` and dependencies) from the current IETF drafts (actually, they are no longer current) because there were a significant improvement over the ones used in `master` (you may have noticed that there is no `keystored` because it is not needed anymore). However, they are still quite a mess and only the useful and supported parts of them were implemented. They are being worked on but it may still take a significant time until they are finished. Until then the configuration is more complex than it needs to be so, depending on your use-case, it may not be suitable for deployment.

Regards,
Michal

**Comment by masif-cs** [comment]
Hi,

Recently while establishing connection between Netopeer2 cli and server using TLS, I used sysrepocfg to merge configuration in ietf-keystore, ietf-truststore, and ietf-netconf-server. After completing merge I saw that I forgot to install oven yang model. After installing all configuration which I merged to ietf-keystore, ietf-truststore, and ietf-netconf-server were lost. Any reason why this happened?

Are we suppose to install all yang models before going for updating configuration files. During run time cant we install any yang models?

**Comment by michalvasko** [comment]
Hi,
you would have to provide more details but there is no reason a configuration should just disappear. Also, you are right that you cannot install (or uninstall) YANG modules during run-time and if you do uninstall a module, all its configuration is lost, which I believe makes sense.

So, if you can provide the exact steps (commands) so that I can reproduce the problem, I can explain why it happened or fix any incorrect behavior, otherwise I cannot help.

Regards,
Michal

**Comment by masif-cs** [comment]
Hi,

Below are the steps I followed:
1.  Compile and install sysrepo, netopeer2 and libyang all from devel branch.
**libnetconf:**
cd /home/airvana/masif/netconf/libnetconf2/build
cmake -DENABLE_TLS=ON -DENABLE_SSH=ON ..
make
make install

**Sysrepo:**
cd /home/airvana/masif/netconf/sysrepo/build
cmake -DCMAKE_BUILD_TYPE=Debug ..
make
make install

make sr_clean

**Netopeer2**
cd /home/airvana/masif/netconf/Netopeer2/server/build
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
make
make install

2. Now I run below commands to merge TLS related changes to configuration files:
sysrepocfg --edit=vim -m ietf-keystore
sysrepocfg --edit=vim -m ietf-truststore
sysrepocfg --edit=vim -m ietf-netconf-server

3. After all changes are done, I do install/uninstall of any yang model(as of now tried with Oven), and I see all changes which I made in step 2 is gone.

**Comment by michalvasko** [comment]
Hi,
you are right, this use-case did not work properly. If you update *sysrepo* (https://github.com/sysrepo/sysrepo/commit/d7d1c4cc287572a0e925e66320161b0a41550a22), it should no longer get deleted.

Regards,
Michal

**Comment by masif-cs** [comment]
Hi,

Thanks for quick fix. It is working fine now.
