### ISSUE TITLE
Control logging of libnetconf

### ISSUE THREAD

**Issue by meghna-doshi** [CESNET/netopeer2#493]
Hi,
When we used standalone libnetconf, we were getting the RPC logs. 
With netopeer2, we are not getting any of the RPC logs from libnetconf. 
Can you please tell where are we controlling the libnetconf logging in netopeer and how can we enable the logging of the RPC etc. from libnetconf.

Regards,
Meghna

**Comment by michalvasko** [comment]
Hi Meghna,
you need to compile *netopeer2* in `debug` mode and then use `-c` logging option (look at help for the parameters).

Regards,
Michal

**Comment by himaniadsar** [comment]
Hi,
How to get sys logs in Netopeer 2 at run time?

Regards,
Himani

**Comment by michalvasko** [comment]
Use `-d -v2` parameters, for example.

**Comment by himaniadsar** [comment]
Thank you
I'm able to get the logs. 

**But I want to see the logs running continuously.
Can you please suggest.**


root@5da917afcde7:/# netopeer2-server -d -v2
[INF]: LY: Plugin "/usr/lib/x86_64-linux-gnu/libyang1/extensions/nacm.so" successfully loaded.
[INF]: LY: Plugin "/usr/lib/x86_64-linux-gnu/libyang1/extensions/metadata.so" successfully loaded.
[INF]: LY: Plugin "/usr/lib/x86_64-linux-gnu/libyang1/extensions/yangdata.so" successfully loaded.
[INF]: LY: Plugin "/usr/lib/x86_64-linux-gnu/libyang1/user_types/user_yang_types.so" successfully loaded.
[INF]: LY: Plugin "/usr/lib/x86_64-linux-gnu/libyang1/user_types/user_inet_types.so" successfully loaded.
[INF]: LY: Reading module "ietf-yang-metadata".
[INF]: LY: Module "ietf-yang-metadata@2016-08-05" successfully parsed as implemented.
[INF]: LY: Reading module "yang".
[INF]: LY: Resolving "yang" unresolved schema nodes and their constraints...
[INF]: LY: All "yang" schema nodes and constraints resolved.
[INF]: LY: Module "yang@2017-02-20" successfully parsed as implemented.
[INF]: LY: Reading module "ietf-inet-types".
[INF]: LY: Resolving derived type "union" failed, it will be attempted later.
[INF]: LY: Resolving derived type "union" failed, it will be attempted later.
[INF]: LY: Resolving derived type "union" failed, it will be attempted later.
[INF]: LY: Resolving derived type "union" failed, it will be attempted later.
[INF]: LY: Resolving "ietf-inet-types" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-inet-types" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-inet-types@2013-07-15" successfully parsed as implemented.
[INF]: LY: Reading module "ietf-yang-types".
[INF]: LY: Module "ietf-yang-types@2013-07-15" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-yang-types" in /etc/sysrepo/yang.
[INF]: LY: Resolving "sysrepo" unresolved schema nodes and their constraints...
[INF]: LY: All "sysrepo" schema nodes and constraints resolved.
[INF]: LY: Module "sysrepo@2021-01-18" successfully parsed as implemented.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Scheduled changes not applied because of other existing connections.
[INF]: LY: Searching for "ietf-datastores" in /etc/sysrepo/yang.
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-datastores@2018-02-14.yang" file.
[INF]: LY: Module "ietf-datastores@2018-02-14" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-yang-library" in /etc/sysrepo/yang.
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-yang-library@2019-01-04.yang" file.
[INF]: LY: Searching for "ietf-inet-types" in /etc/sysrepo/yang.
[INF]: LY: Searching for "ietf-datastores" in /etc/sysrepo/yang.
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-datastores@2018-02-14.yang" file.
[INF]: LY: Module "ietf-yang-library@2019-01-04" successfully parsed as implemented.
[INF]: LY: Searching for "sysrepo-monitoring" in /etc/sysrepo/yang.
[INF]: LY: Loading schema from "/etc/sysrepo/yang/sysrepo-monitoring@2021-01-15.yang" file.
[INF]: LY: Resolving "sysrepo-monitoring" unresolved schema nodes and their constraints...
[INF]: LY: All "sysrepo-monitoring" schema nodes and constraints resolved.
[INF]: LY: Module "sysrepo-monitoring@2021-01-15" successfully parsed as implemented.
[INF]: LY: Searching for "sysrepo-plugind" in /etc/sysrepo/yang.
[INF]: LY: Loading schema from "/etc/sysrepo/yang/sysrepo-plugind@2020-12-10.yang" file.
[INF]: LY: Module "sysrepo-plugind@2020-12-10" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-netconf-with-defaults" in /etc/sysrepo/yang.
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-netconf-with-defaults@2011-06-01.yang" file.
[INF]: LY: Searching for "ietf-netconf" in /etc/sysrepo/yang.
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-netconf@2013-09-29.yang" file.
[INF]: LY: Searching for "ietf-netconf-acm" in /etc/sysrepo/yang.
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-netconf-acm@2018-02-14.yang" file.
[INF]: LY: Module "ietf-netconf-acm@2018-02-14" successfully parsed as imported.
[INF]: LY: Module "ietf-netconf@2013-09-29" successfully parsed as imported.
[INF]: LY: Resolving "ietf-netconf-with-defaults" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-netconf-with-defaults" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-netconf-with-defaults@2011-06-01" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-netconf-notifications" in /etc/sysrepo/yang.
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-netconf-notifications@2012-02-06.yang" file.
[INF]: LY: Resolving "ietf-netconf-notifications" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-netconf-notifications" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-netconf-notifications@2012-02-06" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-origin" in /etc/sysrepo/yang.
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-origin@2018-02-14.yang" file.
[INF]: LY: Searching for "ietf-yang-metadata" in /etc/sysrepo/yang.
[INF]: LY: Resolving "ietf-origin" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-origin" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-origin@2018-02-14" successfully parsed as implemented.
[INF]: LY: Module "ietf-netconf-acm@2018-02-14" now implemented.
[INF]: LY: Searching for "ietf-netconf-monitoring" in /etc/sysrepo/yang.
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-netconf-monitoring@2010-10-04.yang" file.
[INF]: LY: Module "ietf-netconf-monitoring@2010-10-04" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-netconf-nmda" in /etc/sysrepo/yang.
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-netconf-nmda@2019-01-07.yang" file.
[INF]: LY: Searching for "ietf-origin" in /etc/sysrepo/yang.
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-origin@2018-02-14.yang" file.
[INF]: LY: Searching for "ietf-netconf-with-defaults" in /etc/sysrepo/yang.
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-netconf-with-defaults@2011-06-01.yang" file.
[INF]: LY: Resolving "ietf-netconf-nmda" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-netconf-nmda" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-netconf-nmda@2019-01-07" successfully parsed as implemented.
[INF]: LY: Searching for "nc-notifications" in /etc/sysrepo/yang.
[INF]: LY: Loading schema from "/etc/sysrepo/yang/nc-notifications@2008-07-14.yang" file.
[INF]: LY: Searching for "notifications" in /etc/sysrepo/yang.
[INF]: LY: Loading schema from "/etc/sysrepo/yang/notifications@2008-07-14.yang" file.
[INF]: LY: Module "notifications@2008-07-14" successfully parsed as imported.
[INF]: LY: Module "nc-notifications@2008-07-14" successfully parsed as implemented.
[INF]: LY: Module "notifications@2008-07-14" now implemented.
[INF]: LY: Searching for "ietf-x509-cert-to-name" in /etc/sysrepo/yang.
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-x509-cert-to-name@2014-12-10.yang" file.
[INF]: LY: Module "ietf-x509-cert-to-name@2014-12-10" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-crypto-types" in /etc/sysrepo/yang.
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-crypto-types@2019-07-02.yang" file.
[INF]: LY: Module "ietf-crypto-types@2019-07-02" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-keystore" in /etc/sysrepo/yang.
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-keystore@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-crypto-types" in /etc/sysrepo/yang.
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-crypto-types@2019-07-02.yang" file.
[INF]: LY: Resolving "ietf-keystore" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-keystore" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-keystore@2019-07-02" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-truststore" in /etc/sysrepo/yang.
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-truststore@2019-07-02.yang" file.
[INF]: LY: Module "ietf-truststore@2019-07-02" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-tcp-common" in /etc/sysrepo/yang.
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-tcp-common@2019-07-02.yang" file.
[INF]: LY: Module "ietf-tcp-common@2019-07-02" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-ssh-server" in /etc/sysrepo/yang.
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-ssh-server@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-ssh-common" in /etc/sysrepo/yang.
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-ssh-common@2019-07-02.yang" file.
[INF]: LY: Module "ietf-ssh-common@2019-07-02" successfully parsed as imported.
[INF]: LY: Searching for "ietf-keystore" in /etc/sysrepo/yang.
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-keystore@2019-07-02.yang" file.
[INF]: LY: Searching for "iana-crypt-hash" in /etc/sysrepo/yang.
[INF]: LY: Loading schema from "/etc/sysrepo/yang/iana-crypt-hash@2014-08-06.yang" file.
[INF]: LY: Module "iana-crypt-hash@2014-08-06" successfully parsed as imported.
[INF]: LY: Module "ietf-ssh-server@2019-07-02" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-tls-server" in /etc/sysrepo/yang.
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-tls-server@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-tls-common" in /etc/sysrepo/yang.
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-tls-common@2019-07-02.yang" file.
[INF]: LY: Module "ietf-tls-common@2019-07-02" successfully parsed as imported.
[INF]: LY: Searching for "ietf-truststore" in /etc/sysrepo/yang.
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-truststore@2019-07-02.yang" file.
[INF]: LY: Module "ietf-tls-server@2019-07-02" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-netconf-server" in /etc/sysrepo/yang.
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-netconf-server@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-x509-cert-to-name" in /etc/sysrepo/yang.
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-x509-cert-to-name@2014-12-10.yang" file.
[INF]: LY: Searching for "ietf-tcp-client" in /etc/sysrepo/yang.
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-tcp-client@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-tcp-common" in /etc/sysrepo/yang.
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-tcp-common@2019-07-02.yang" file.
[INF]: LY: Module "ietf-tcp-client@2019-07-02" successfully parsed as imported.
[INF]: LY: Searching for "ietf-tcp-server" in /etc/sysrepo/yang.
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-tcp-server@2019-07-02.yang" file.
[INF]: LY: Module "ietf-tcp-server@2019-07-02" successfully parsed as imported.
[INF]: LY: Resolving "ietf-netconf-server" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-netconf-server" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-netconf-server@2019-07-02" successfully parsed as implemented.
[INF]: SR: Connection 24 created.
[INF]: SR: Session 36 (user "root", CID 24) created.
[ERR]: SR: RPC subscription for "/ietf-netconf:get-config" with priority 0 already exists.
[ERR]: NP: Subscribing for "/ietf-netconf:get-config" RPC failed (Invalid argument).
[ERR]: NP: Server RPC subscribe failed.
[INF]: NP: Server terminated.

Regards,
Himani

**Comment by michalvasko** [comment]
What do you mean? They would be "continuous" if the server was running continuously but it has terminated, obviously. You likely already have another server instance running in the background, you cannot have more than 1.

**Comment by himaniadsar** [comment]
I meant I want to see the logs in real time ( I should be able to see the logs parallelly if I do get config, edit config, etc,  just like how we can see when we do tail log file).

(Is it like if we use -d, it will terminate current running netopeer2 server and restart new netopeer2 server with debug mode? )

**Comment by michalvasko** [comment]
> I meant I want to see the logs in real time

Yes, you will see all the logs for everything that happens on the server in real-time with the command I mentioned. The problem here is that you most likely have a *netopeer2-server* instance already running on your system but you have executed it without `-d` meaning it was daemonized so it is running in the background. That is why when you try to run it with the parameters, it is not able to start and terminates (there are errors printed meaning something is wrong), there can only be a single server instance running. I have nothing more to tell you, please try to get familiar with the terms I am using if you do not understand them.

**Comment by Ghghtr7845** [comment]
How do I view the log in a .log file, and not on the terminal? Is there a way to pipe all these messages into a log file? I tried netopeer2-server -d -v3 | tee -a /var/log/netopeer2.log, but it doesn't work. The message keeps showing up in the terminal and the log file remains empty.
