### ISSUE TITLE
Undefined reference to _findfirst, _findnext & _findclose functions when building sysrepo in qnx

### ISSUE THREAD

**Issue by SumukhNiketan** [CESNET/netopeer2#494]
Hi,

I am building sysrepo for qnx environment while I get the below errors.

libsysrepo.so.0.7.8: undefined reference to `_findfirst'
libsysrepo.so.0.7.8: undefined reference to `_findnext'
libsysrepo.so.0.7.8: undefined reference to `vdprintf'
libsysrepo.so.0.7.8: undefined reference to `_findclose'

For vdprintf I got the implementation and added for which the error got cleared.

Are these functions not available for qnx or should I do similar thing. ie; Add implementations for the _findfirst, _findnext & _findclose .

If so can anyone please provide me the implementations for the above said functions

**Comment by michalvasko** [comment]
Hi,
firstly, why have you created the issue in *netopeer2*?

Anyway, I am not sure what these functions do because they are not called directly by *sysrepo* code. That could mean they are from a dependent library (tree manipulation maybe?).  I have nothing to go on here so I cannot really help you.

Regards,
Michal
