### ISSUE TITLE
Inconsistency (?) between netopeer2 and sysrepo

### ISSUE THREAD

**Issue by syyyr** [CESNET/Netopeer2#500]
Hello,
I found a little bit of an inconsistency between Netopeer2 and Sysrepo. I have this schema:
```yang
module example-schema {
    prefix aha;
    namespace "http://example.com";

    list animalWithColor {
        key 'name color';
        leaf name {
            type string;
        }
        leaf color {
            type string;
        }
    }
}
```
and this data:
```xml
<animalWithColor xmlns="http://example.com">
  <name>Dog</name>
  <color>brown</color>
</animalWithColor>
<animalWithColor xmlns="http://example.com">
  <name>Dog</name>
  <color>white</color>
</animalWithColor>
<animalWithColor xmlns="http://example.com">
  <name>Cat</name>
  <color>grey</color>
</animalWithColor>
```
Now, I want to get all the `name` leafs inside the list (to tell the user, which values are valid for `name` when addressing `animalWithColor`). That means all nodes with this xpath: 
`/example-schema:animalWithColor/name`

I want to do this through Sysrepo and also through Netopeer2. I created a sample program which does this:
```cpp
#include <iostream>
#include <libyang/Tree_Data.hpp>
#include <sysrepo-cpp/Session.hpp>
extern "C" {
#include <nc_client.h>
}

int main(int argc, char* argv[])
{
    std::cout << "SYSREPO" << std::endl << "==============" << std::endl;
    auto conn = std::make_shared<sysrepo::Connection>("name");
    auto sess = std::make_shared<sysrepo::Session>(conn);
    auto items = sess->get_items("/example-schema:animalWithColor/name");
    for (unsigned int i = 0; i < items->val_cnt(); i++) {
        std::cout << items->val(i)->xpath() << " = " << items->val(i)->val_to_string() << std::endl;
    }


    std::cout << std::endl << "NETCONF" << std::endl << "==============" << std::endl;
    nc_client_init();
    auto session = nc_connect_unix("/home/vk/git/netconf-cli/build/netopeer2-server.sock", nullptr);
    auto rpc = nc_rpc_getconfig(NC_DATASTORE_RUNNING, "/example-schema:animalWithColor/name", NC_WD_ALL, NC_PARAMTYPE_CONST);
    uint64_t msgid;
    nc_send_rpc(session, rpc, 10000, &msgid);
    struct nc_reply_data* reply;
    nc_recv_reply(session, rpc, msgid, 100000, 0, (struct nc_reply**) &reply);
    auto dataNode = libyang::create_new_Data_Node(reply->data);
    for (const auto& it : dataNode->tree_for()) {
        for (const auto& node : it->tree_dfs()) {
            std::cout << node->path();
            if (node->schema()->nodetype() == LYS_LEAF) {
                libyang::Data_Node_Leaf_List leaf(node);
                std::cout <<  " = " << leaf.value_str();
            }
            std::cout << std::endl;
        }
    }
}
```
This is the output of the program:
```
SYSREPO
==============
/example-schema:animalWithColor[name='Dog'][color='brown']/name = Dog
/example-schema:animalWithColor[name='Dog'][color='white']/name = Dog
/example-schema:animalWithColor[name='Cat'][color='grey']/name = Cat

NETCONF
==============
/example-schema:animalWithColor[name='Dog'][color='brown']
/example-schema:animalWithColor[name='Dog'][color='brown']/name = Dog
/example-schema:animalWithColor[name='Dog'][color='brown']/color = brown
/example-schema:animalWithColor[name='Dog'][color='white']
/example-schema:animalWithColor[name='Dog'][color='white']/name = Dog
/example-schema:animalWithColor[name='Dog'][color='white']/color = white
/example-schema:animalWithColor[name='Cat'][color='grey']
/example-schema:animalWithColor[name='Cat'][color='grey']/name = Cat
/example-schema:animalWithColor[name='Cat'][color='grey']/color = grey
```
Sysrepo gives me the `name` leafs only (that's what I wanted), but Netopeer2 also gives me the `color` leafs, which are also present in the list, but they definitely do not fit the `/example-schema:animalWithColor/name` xpath. How would I go about getting only the `name` leafs with Netopeer? Is this the expected behavior? Should I just filter the Netopeer results by the xpath? Or is there a better approach?

**Comment by michalvasko** [comment]
Hi,
okay, this took me a second to figure out but it all makes sense. Actually, the data returned are the same, your output differences are caused by different data representations and their transformation for display.

If you look at the first line of `SYSREPO` output
```
/example-schema:animalWithColor[name='Dog'][color='brown']/name = Dog
```
you see that there is a list instance (`/example-schema:animalWithColor`), its first key with value (`name='Dog'`) and its second key with value (`color='brown'`). In the `NETCONF` output you start with a data tree representation, so this are the same data
```
example-schema:animalWithColor (1)
     /               \
name='Dog' (2)   color='brown' (3)
```
The difference appears when you call `path()` method for each data node because it always prints a full path of each node
```
/example-schema:animalWithColor[name='Dog'][color='brown'] (1)
/example-schema:animalWithColor[name='Dog'][color='brown']/name = Dog (2)
/example-schema:animalWithColor[name='Dog'][color='brown']/color = brown (3)
```

So, how to achieve what you want? The thing is that even *sysrepo* internally start with this data tree, then uses the XPath filter and gets the XPath in the `sr_val_t` structure by calling `path()` on each selected node. So, you can do the same, call XPath filter (`find_node()`) again on the returned data.

I guess the confusing thing is that you have to use the filter twice. However, in other word, the reason is that you want just the `name` node but it cannot really exist without its parent list, which must also always include all keys. I hope I have explained it enough to be understandable.

Regards,
Michal

**Comment by syyyr** [comment]
Okay, I understand. Thank you for the explanation!
