### ISSUE TITLE
Using Netopeer2 Docker to verify our java netconf client possible

### ISSUE THREAD

**Issue by eraonel** [CESNET/netopeer2#520]
Hi 
Thanks for an excellent Netopeer2 Docker installation. I was able to run it on windows.

I manged to configure it but not with the existing file:

[ssh_callhome](https://github.com/CESNET/Netopeer2/blob/master/server/example_configuration/ssh_callhome.xml)

but with:
```xml
<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
<call-home>
   <netconf-client>
      <name>default-client</name>
      <ssh>
        <endpoints>
          <endpoint>
            <name>test_ssh_ch_endpt</name>
            <address>localhost</address>
            <port>4334</port>
          </endpoint>
        </endpoints>
        <host-keys>
          <host-key>
            <name>test_ssh_callhome_key</name>
            <public-key>ssh_host_rsa_key</public-key>
          </host-key>
        </host-keys>
      </ssh>
      <connection-type>
        <persistent/>
      </connection-type>
    </netconf-client>
</call-home>
</netconf-server> 
```
Anyway I started with:
```
listen
Waiting 60s for an SSH Call Home connection on port 4334...
```
And I got the connection.... so far everything is fine.

Now I want to use our java NETCONF client to make sure it can handle "Call Home" form Netopeer2-server.
I keept server running and then I start our netconf client.
```
2020-01-09 13:12:56,545 (RequestHandler.java:31)  INFO : Call Home  listening on port [4334]
2020-01-09 13:12:56,549 (RequestHandler.java:46)  INFO : Waiting to accept connection...
```
and nothing happens. So I am guessing that 4334 is never exposed from the Docker container.
I checked:
https://github.com/sysrepo-archive/docker-sysrepo-netopeer2/blob/master/Dockerfile
only
```
EXPOSE 830
```
Is it possible to expose:
4334 (SSH)
4335 (TLS)
so clients outside docker can be verified?

Or do I need to make my own copy of the docker file?

//mike

**Comment by michalvasko** [comment]
Hi,
you are best writing your own Docker file because this one is obsolete. Also, you must have run the image quite some time ago because it cannot be working with the current `master` branches of *sysrepo*, *libnetconf2*, and *netopeer2*. If you switch to `legacy` branch in all these repositories, you should be fine.

Regards,
Michal

**Comment by eraonel** [comment]
Hi Michal,
I used the following command 
docker run -it --name sysrepo -p 830:830 --rm sysrepo/sysrepo-netopeer2:latest
from here:
[docker](https://hub.docker.com/r/sysrepo/sysrepo-netopeer2/)
Just to confirm if I am on the correct track, do you think exposing 
4334 (SSH)
4335 (TLS)
would help in verification of our NETCONF client support for call home?

br,

//mikael

**Comment by michalvasko** [comment]
Hi,
ah, okay, this Dockerfile clones the new *sysrepo* but it still includes some old commands
```dockerfile
# keystore
RUN \
      cd /opt/dev && \
      git clone https://github.com/CESNET/Netopeer2.git && \
      cd Netopeer2 && \
      ## cd keystored && mkdir build && cd build && \
      git checkout devel-server && \
      cmake -DCMAKE_BUILD_TYPE:String="Debug" .. && \
      make -j2 && \
      make install && \
      ldconfig
```
because there is no `keystored` and this directory is not in the repository anymore. So I am not sure how you could have successfully run it. But yes, exposing the Call Home ports should fix your problem.

Regards,
Michal

**Comment by eraonel** [comment]
ok.  Where can I find the complete new docker file and download?

**Comment by eraonel** [comment]
Trying to build new docker image
Cloning into 'Netopeer2'...
Switched to a new branch 'devel-server'
Branch 'devel-server' set up to track remote branch 'devel-server' from 'origin'.
CMake Error: The source directory "/opt/dev" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

Any ideas?
br,

//mike

**Comment by eraonel** [comment]
I manged to get past 'making' Netopeer2/server. Using:
# keystore
#RUN \
     # cd /opt/dev && \
      #git clone https://github.com/CESNET/Netopeer2.git && \
      #cd Netopeer2 && \
      #cd keystored && mkdir build && cd build && \
      #git checkout devel-server \
      #cmake -DCMAKE_BUILD_TYPE:String="Debug" .. && \
      #make -j2 && \
      #make install && \
      #ldconfig

# netopeer2
RUN \
      #cd /opt/dev && \
      git clone -b devel-server https://github.com/CESNET/Netopeer2.git && \
      #git checkout devel-server \
      cd Netopeer2/server && mkdir build && cd build && \
      cmake -DCMAKE_BUILD_TYPE:String="Debug" .. && \
      make -j2 && \
      make install && \
      cd ../../cli && mkdir build && cd build && \
      cmake -DCMAKE_BUILD_TYPE:String="Debug" .. && \
      make -j2 && \
      make install

Then I fail on:
Step 16/17 : COPY supervisord.conf /etc/supervisord.conf
COPY failed: stat /var/lib/docker/tmp/docker-builder152758300/supervisord.conf: no such file or directory

Where is supervisord.conf located?

**Comment by lcbcFoo** [comment]
I am currently using this dockerfile from sysrepo repository to run netopeer2 + sysrepo (https://github.com/sysrepo/sysrepo/tree/master/deploy/docker/sysrepo-netopeer2). Note you will need all files in that directory, one of them is the supervisord.conf you are lacking.

The only things I personally change are:
- checkout to devel-server branch in the Netopeer2 section of Dockerfile instead of master. 
- change supervisord.conf autorestart in netopeer2 section to false, since sometimes I want do kill netopeer2-server process and run it again manually without killing the container.

However, it is worth saying I don't know if it is the most recent/stable docker build, it is just the one I got working for know.
