### ISSUE TITLE
Netopeer Client

### ISSUE THREAD

**Issue by masif-cs** [CESNET/netopeer2#524]
Hi,

Is there any specific open source software which has netopeer client code which can create multiple session and handle multiple request from netopeer server?

**Comment by michalvasko** [comment]
Hi,
by "netopeer client code" I will assume a client built using *libnetconf2*. Our focus was always on the server and hence *libnetconf2* does really support any advanced client functionality. However, the code should be fairly well-written and so if anyone wanted to write such a NETCONF client, they could take *libnetconf2* and just add all the required functions on top of the existing ones, to put it simply. But to answer you, no, there is no advanced *libnetconf2* based client because it is missing support for such functionality.

Regards,
Michal

**Comment by masif-cs** [comment]
Hi,

I got you point. Actually I am planning to write NETCONF client based on libnetconf2. I am planning to use Netopeer2 cli as reference.

Is any functionality missing in current cli code?
What do you mean by well-written? Same cli code need to be more organized or more functionalities need to be added?

**Comment by michalvasko** [comment]
Hi,
okay, I have forgotten that some changes were made in the structure organization so even the client does support more functionality that is used in *netopeer2-cli* but it is all managed implicitly. What I mean can be seen in [session_client.c](https://github.com/CESNET/libnetconf2/blob/master/src/session_client.c#L135), every thread uses its own context (options). If you want to write an advanced (multi-threaded) client, you will have to understand that code anyway, so that is the place I suggest you start at.

Anyway, the difference between server and client now is that in server you manage your options manually (explicitly).

Regards,
Michal

**Comment by jktjkt** [comment]
Just to add one more random reference, we're also working on an [interactive NETCONF CLI called, well, `netconf-cli`](https://github.com/CESNET/netconf-cli) which uses `libnetconf2` internally. We do not support concurrent NETCONF connections from the UI (it's currently hard-wired to `sysrepo` via a local socket), but the test suite covers NETCONF connections, so this part works. I don't think we're doing concurrency or asynchronous access, though, but perhaps it will help you anyway.
