### ISSUE TITLE
Query : How keystored sysrepo plugin implemented in new netopeer2 implementation

### ISSUE THREAD

**Issue by sriramkandukuri** [CESNET/Netopeer2#525]
Hi,

Could you please give some information regarding new netopeer2 for achieving keystored plugin in earlier version.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi,
the main difference is that `keystored` implemented a sort-of key store by managing all the SSH keys and certificates and making sure that the server can get them when it was needed. The reason was that they could not be directly stored in the YANG configuration. Using the updated modules this was possible so `keystored` was no longer needed.

As an example, you can look at how server host keys were retrieved. The [callback](https://github.com/CESNET/Netopeer2/blob/legacy/server/ietf_keystore.c#L25) in the old *netopeer2* returned the exact path of the key where it knew `keystored` will store the actual key. The new [callback](https://github.com/CESNET/Netopeer2/blob/master/server/netconf_server_ssh.c#L36) simply returns the key data because they are stored directly in the configuration. This mechanism is also much more robust.

Regards,
Michal
