### ISSUE TITLE
Callhome without authentication over SSH

### ISSUE THREAD

**Issue by masif-cs** [CESNET/Netopeer2#533]
Hi,

I am trying to do callhome over ssh. But on client side it is prompting for "Are you sure you want to continue connecting Yes/No" and after this asking for server password. As server client connection should be automatic, so can you please tell me how to avoid it? It there any configuration i need to add?

Normally we use sshpass while doing for console but in this case I am not sure how to achieve it. Could you please help?

**Comment by michalvasko** [comment]
Hi,
the simplest thing to do is to use SSH key authentication. Otherwise you would have to define your own *libnetconf2* `password` authentication callback that would not require user input (not use *netopeer2-cli*).

Regards,
Michal

**Comment by masif-cs** [comment]
Hi Michal,

I didnt get your point.
What do you mean by SSH Key authentication?
Where to add this password callback?

I can see in configuration file where it is asking for client authentication as interactive. Do we need to change something here to add the password here itself?
<client-authentication>
                                <supported-authentication-methods>
                                    <publickey/>
                                    <passsword/>
                                    <other>interactive</other>
                                </supported-authentication-methods>
                                <users/>
                            </client-authentication>

**Comment by michalvasko** [comment]
Hi,
I am not sure what you did not get but I will try to add some details. There are 3 SSH authentications supported by *libnetconf2*, `publickey`, `password`, and `interactive`. If you want to use *netopeer2-cli* to listen for Call Home connection and not ask the user for the password interactively, you should use the `publickey` SSH authentication. You should definitely know what it is, easy to find some basic information about it. For starters, you need to have an SSH public/private key pair (usually there is one in `~/.ssh/` named `id_rsa` and `id_rsa.pub`, for instance). To configure it as authorized for *netopeer2*, just add it into `authorized_keys` file in your user directory `~/.ssh`. To configure it for the client, use the `auth keys add` command (`auth -h`). If you have more questions regarding each step, try looking for answers yourself, these are quite standard steps.

As for the callback, like I said, you would have to define your [own callback](https://github.com/CESNET/libnetconf2/blob/master/src/session_client.h#L218) for `password` authentication so that you can supply the password non-interactively. But you probably do not want to write your own NETCONF client, so use the SSH keys.

Regards,
Michal

**Comment by masif-cs** [comment]
Hi,

Actually I am writing my own client. I will try using the callback.

I have one more question, normally if we use netopeer-cli we have to give the XML input when we do edit config rpc. Is there any way to generate XML input from XPATH or something? We will have message structure which needs to be send to netopeer-server, how do we convert them to XML format automatically?

**Comment by michalvasko** [comment]
Hi,
what you want our tools do not allow. [pyang](https://github.com/mbj4668/pyang) output `sample-skeleton` generates something like that but I think you still need to add specific values, not sure.

Regards,
Michal

**Comment by masif-cs** [comment]
Hi,

Ok Thanks. I will try out the pyang stuff.
I am trying the password callback for SSH. I wrote the callback func and used below api's to enable password authentication using SSH.

nc_client_ssh_set_auth_pref(NC_SSH_AUTH_PASSWORD, 1);
nc_client_ssh_set_auth_pref(NC_SSH_AUTH_PUBLICKEY, -1);
nc_client_ssh_set_auth_pref(NC_SSH_AUTH_INTERACTIVE, -1);
nc_client_ssh_set_auth_password_clb(getPassword, "DATA");

It is not working after doing this. Do I need to change the configuration file on server side too? Am I doing something wrong?

**Comment by michalvasko** [comment]
Hi,
oh, my bad, sorry. You actually want to set another callback, one for [checking server host key](nc_client_ssh_set_auth_hostkey_check_clb). But you still need to solve non-interactive authentication somehow and `password` callback is probably the easiest solution.

Regards,
Michal

**Comment by masif-cs** [comment]
Hi,

The link you gave is not working.
Using password callback will make it non-interactive right?

**Comment by michalvasko** [comment]
Hi,
sorry about the link, a copy-paste error, should be correct now. Yes, when you define your own callback, only it will be executed, the default callback is interactive. And it is possible pyang 2.1 does not support it, it is a really old version.

Regards,
Michal

**Comment by masif-cs** [comment]
Hi,

Its not working, not sure what I am doing wrong. Below is code:
And What is the pyang version I need to use?
       

>  nc_client_ssh_ch_set_username(user);
> 	nc_client_ssh_ch_add_bind_listen(host, port);
> 	nc_client_ssh_set_auth_pref(NC_SSH_AUTH_PASSWORD, 1);
> 	nc_client_ssh_set_auth_pref(NC_SSH_AUTH_PUBLICKEY, -1);
> 	nc_client_ssh_set_auth_pref(NC_SSH_AUTH_INTERACTIVE, -1);
> 	nc_client_ssh_set_auth_password_clb(getPassword, "DATA");
> 	nc_client_ssh_set_auth_hostkey_check_clb(getHostKey, "DATA");
> 		
> 	while(1)
> 	{		
> 		printf("Waiting %ds for an SSH Call Home connection on port %u...\n", timeout, port);
> 		
> 		/* create the session */
> 		ret = nc_accept_callhome(timeout * 1000, NULL, &session);
> 		
> 		if (ret != 1)
> 		{
> 			if (ret == 0)
> 			{
> 				printf("%s: Receiving SSH Call Home on port %d as user \"%s\" timeout elapsed.",__FUNCTION__,port,user);
> 				//ERROR("my_call_home", "Receiving SSH Call Home on port %d as user \"%s\" timeout elapsed.", port, user);
> 			} else
> 			{
> 				printf("%s: Receiving SSH Call Home on port %d as user \"%s\" failed.",__FUNCTION__,port,user);
> 				//ERROR("my_call_home", "Receiving SSH Call Home on port %d as user \"%s\" failed.", port, user);
> 			}
> 		}
> 		else
> 		{
> 			printf("Connection established with host : [%s] : [%s] : [%s] : [%d]\n", session->username, session->path, session->host, session->port);
> 			printf("Session Obj : [%p] NC ID : [%d] NC Status : [%d]\n",session, session->id, session->status);
> 			DuRuClientThread *pDuRuClientThread = new DuRuClientThread(session);
> 		}

**Comment by michalvasko** [comment]
Hi,
I may be partly to blame, but it was a long time since I have worked with *libnetconf2*. It seems all the functions `nc_client_ssh_set_*` have actually a Call Home variant `nc_client_ssh_ch_set_*` that you should use instead. However, saying "its not working" is not very helpful so please specify the problem in a bit more detail next time.

As for the *pyang* version, I have no idea since when the output was added, why don't you find out for yourself.

Regards,
Michal

**Comment by masif-cs** [comment]
Hi Michal,

I used the above code and just replaced all nc_client_ssh_set_* to nc_client_ssh_ch_set_*, I am getting segmentation fault on client. No other logs are coming on client side.

One separate question:
Is there any rpc/api to check if the netconf session still exist or the connectivity is still intact with netconf server?

**Comment by michalvasko** [comment]
Hi,
seems it is finally working but you are doing something in your callback that you should not. Can you run the client with `valrgind`, for example?

As for your other question, not really as there is no such functionality defined for NETCONF. But if you enable keep-alives, the connection should get terminated and on any next communication you should get a proper NETCONF error.

Regards,
Michal

**Comment by masif-cs** [comment]
Hi Michal,

Thanks it worked. Some issue with my callback function.

**Comment by kchakki2020** [comment]
Hi,
I have some queries very closely related to this topic. Can I use this thread or should raise a new one? Please let me know, just joined the club.
Thanks
Chakki

**Comment by michalvasko** [comment]
Hi,
please start a new thread, this issue is long as enough as it is.

Regards,
Michal
