### ISSUE TITLE
KeepAlive on Netopeer server

### ISSUE THREAD

**Issue by masif-cs** [CESNET/netopeer2#544]
Hi @michalvasko ,

I want to know little bit about keep alive supported by Netopeer server. Do you have document available for it?

I can see the we configure in ietf-netconf-server to support keep alive. But I dont understand the interval are in second/minutes. What does the other details inside keepalive mean?
```
<keepalives>
     <idle-time>1</idle-time>
     <max-probes>10</max-probes>
     <probe-interval>5</probe-interval>
</keepalives>
```

Is the keepalive received on client side too?
Actually I want to monitor the server from client based on the keepalives. Is it possible to achieve it using keepalives instead of calling extra RPC?

**Comment by michalvasko** [comment]
Hi,
I have already talked about this recently in several issues, but fine, once more, with some extra information. These values configure [TCP keep-alive Linux parameters](https://github.com/CESNET/libnetconf2/blob/master/src/session.c#L137) and they should be enabled for both server and the client. Information about Call Home and SSH keep-alives is summarized in https://github.com/CESNET/libnetconf2/issues/201.

Regards,
Michal

**Comment by IamPatrik** [comment]
Hi Michal, thank you for the answer and the linked issue.
However, this confirms the problem still existed in later versions. Upgrading would be some work, but I can do this. However, as the bug is known, can you tell which version contains the fix? I did not really get this from the linked issue. Note here that doing a configuration on the server to support this is not really an option, as SSH_MSG_GLOBAL_REQUEST is mandatory in the standard and thus not a configuration issue.
BR
Patrik
