### ISSUE TITLE
netopeer2-cli vs ncclient

### ISSUE THREAD

**Issue by tharunprabhu** [CESNET/netopeer2#624]
I'm working on a project with netopeer2 server and I'm not sure which client to choose. I understand that both netopeer2-cli and ncclient can communicate with netopeer2-server. But is one better than the other in any way?

**Comment by michalvasko** [comment]
Hi,
I am not able to tell you much regarding `ncclient` because I have never used it but just looking at their README, it is written in Python and is using *libxml2*. Based on that I would expect its performance to be quite poor. *netopeer2-cli* is written in C and is using native (written specially for the purpose) libraries so you should have no performance problems. At the same time, our CLI was developed mostly for our (testing) purposes and while supporting a lot of features now, I imagine there still much to improve. So, if you only have fairly basic use-cases, you should have no problems with *netopeer2-cli* whatsoever. But if you require some advanced features (such as supporting multiple concurrent sessions or actual configuration), you should probably look elsewhere.

Regards,
Michal

**Comment by tharunprabhu** [comment]
Looks like I'll have to use ncclient as there is need for multiple concurrent sessions. Thanks for your inputs, Michal.
