### ISSUE TITLE
Information request: Server usability/stability.

### ISSUE THREAD

**Issue by darshana-jk** [CESNET/Netopeer2#65]
Sorry if I'm writing this request on the wrong place (issue tracking system).

I want to use the Netopeer2, as the NETCONF server in a PMA implementation.  From my first look I think libnetconf/netopeer has complete coverage over what is required for us. However, I would like to use libnetconf2 as it is new. I would like to know the usability of the Netopeer2 server for that. 

Does the current server implementation stable enough or still highly at development stage as the readme says ?
Does the libnetconf2/Netopeer2 server covers the functionalities/capabilities covered in RFC6241?

Thanks in advance.
Darshana.

**Comment by michalvasko** [comment]
Hi Darshana,
at this point I definitely cannot recommend using the old tools. However, the new ones are not fully ready yet even though a significant progress has been made since we have written that description. Still, I believe the base NETCONF RFC should be covered. NETCONF notifications are in development and will work soon, but only in a basic form without any replay possibility for now. Also, server configuration is very limited (currently not even that works properly), but should be gradually improved in the upcoming weeks.

Regards,
Michal

**Comment by darshana-jk** [comment]
Hi Michal,

Thank you for the information. The time-line we have for this NETCONF/YANG server work is 3-4weeks approx., therefore I assume the libnetconf2/netopeer2 is not going to be an option then.
I'm actually confused about your "at this point I definitely cannot recommend using the old tools" comment, why do you not recommend using the old tools? (assuming we are using a released branch like libnetconf-0.9.x, isn't it stable enough to be used in a production environment).

Regards,
Darshana.

**Comment by michalvasko** [comment]
Hi Darshana,
to reword what I said, as long as you are fine currently not having notifications and not being able to change NETCONF server options run-time (both of which should improve soon), I suggest you use the new tools. We know about several issues in the old ones that will never be fixed (by us) and the old libnetconf is significantly ineffective in many ways. Except that, the support is not that good and it may take quite long to resolve some issues because it simply is not a priority for us, some will not be fixed at all, as I mentioned. Still, it was developed and used for some time, so generally it is well-tested and all basic functions should be reliable and work well.

Regards,
Michal
