### ISSUE TITLE
Register callback copy_config

### ISSUE THREAD

**Issue by Sneha-star** [CESNET/netopeer2#665]
Hi Michal,

This may be a very trivial question but not so familiar with netopeer2. So would appreciate if you could help me to give some pointers on how to register for RPC callback copy_config/lock/unlock operation etc so that it will hit the myCallback.

I saw rpc_subscribe API, is it applicable for the above-mentioned RPC call?
(i.e Can I use rpc_subscribe("/ietf-netconf:lock", mycb) so that the proprietry callback (mycb) handler will also get hit ?)

I know how to subscribe for edit-config etc but not getting how to do for the above RPC.
I could not find any document/example in the doc.
If its there please point the same here, I will go through that.

**Comment by michalvasko** [comment]
Hi,
I do not think it is explicitly mentioned anywhere but can be deduced from *sysrepo* RPC subscriptions description. So, yes, you simply subscribe to it the way you mentioned using `rpc_subscribe()`. Also, I do not really think this needs special section because it is quite advanced feature and you really should know what you are doing when you subscribe to these standard RPCs.

Regards,
Michal

**Comment by Sneha-star** [comment]
Thank you Michal.
Yes, I was able to proceed further using the above APIs.
