### ISSUE TITLE
netopeer2-server with openvswitch

### ISSUE THREAD

**Issue by SilviaFc** [CESNET/netopeer2#672]
Hi,
I'm new with netopeer2. I would like to use it with openvswitch (and then manage it with a network controller such as ONOS or ODL).
Can you give me some hints to start? There is any tutorial or guide to follow? I haven't found anything specific on the web. 

I have also tried to follow the ODL guide, but the docker they propose [here](https://docs.opendaylight.org/en/stable-oxygen/user-guide/netconf-user-guide.html#netconf-connector-netopeer) is  no more available.

Do you have any updated information or docker? 
Thanks.

Regards,
Silvia

**Comment by michalvasko** [comment]
Hi,
there is a [docker image](https://hub.docker.com/r/sysrepo/sysrepo-netopeer2/) but it is not updated that often so you are better off not using it. As for a start, the main component in out NETCONF suite is actually *sysrepo* so that is where you should start and read its [docs](https://netopeer.liberouter.org/doc/sysrepo/master/).

Regards,
Michal

**Comment by SilviaFc** [comment]
Dear Michal,
I've succeeded in creating a new docker with the netopeer2-server and loaded a configuration. I'm also able to edit this.
Now, I have another question.
How can I send this configuration to the device I want to configure? There is a specific procedure?

BR,
Silvia

**Comment by michalvasko** [comment]
Hi Silvia,
you do that with [change subscriptions](https://netopeer.liberouter.org/doc/sysrepo/master/subs.html#change_subs) and your specific code in the callback.
