### ISSUE TITLE
Extending timeout for edit-config command (redux)

### ISSUE THREAD

**Issue by esend7881** [CESNET/netopeer2#683]
This question is really a part of the Issue #673. but since a new version of netopeer2 (1.1.39) has come out and that issue got bogged down and distracted by compilation issues, I wanted to revive my actual problem here. 

I am programming in a config that takes a few seconds for it to fully process:

```
> edit-config --target=running --config=/config.xml
cli_send_recv: Timeout for receiving a reply expired.
```

Order of install:

1. libyang 1.0.184
2. sysrepo 1.4.70
3. libnetconf2 1.1.26
4. netopeer2-cli / netopeer2-server 1.1.39

Specifically as root:
```
git clone https://github.com/CESNET/netopeer2.git --branch v1.1.39 --depth 1 --single-branch /opt/netopeer2
mkdir -p /opt/netopeer2/build
cd /opt/netopeer2/build
cmake -DSYSREPO_TIMEOUT=119 -DRPC_TIMEOUT=120 .. 
make 
ldconfig 
make install
```

The timeout should be 2 minutes, which is at least 10x longer than the process took, so I was not expecting a timeout. I grepped through the netopeer2-server logs and don't see anything about a timeout there either. I'm nor sure if sysrepo produces log files.

**Comment by esend7881** [comment]
I believe I resolved this issue by manually specifying the rpc timeout in my edit config command manually:

```
> edit-config --target=running --rpc-timeout=120 --config=/config.xml
OK
```

And I timed it to my manual sleep of 60 seconds and on the dot, the OK response came in.

**Comment by esend7881** [comment]
@michalvasko - I am wondering though, can the SYSREPO_TIMEOUT and RPC_TIMEOUT be the same value? I.e., in the documentation, RPC_TIMEOUT is supposed to be greater than SYSREPO_TIMEOUT, but can they be the same value, say 120?

`cmake -DSYSREPO_TIMEOUT=120 -DRPC_TIMEOUT=120 .. `

**Comment by michalvasko** [comment]
Hi,
I understand the way it is currently is a bit non-intuitive but it was changed several times already and should at least be working correctly now. Generally, the `RPC_TIMEOUT` may not even be needed to be adjustable but encountering so many problems with these timeouts, I would prefer to keep it this way for some slower platforms.

Note that the timeouts really cannot be equal because the `RPC_TIMEOUT` will always wait for `SYSREPO_TIMEOUT` plus some time needed for internal *sysrepo* RPC processing. Meaning if `RPC_TIMEOUT` was <= `SYSREPO_TIMEOUT`, it would effectively override the latter timeout. Hence the compile-time check.

Regards,
Michal
