### ISSUE TITLE
Can't recieve notification after install private yang model.

### ISSUE THREAD

**Issue by LilyCuili** [CESNET/netopeer2#694]
Hi Michal
	When I install private yang model with namespace like "  namespace "http://www.netcom.com/yang/rdvp/upgrade";", from Opendaylight client,can't revieve notification,  but from netopeer cli can get it. Do you know the reason? Is there any limitation about this format of namespace.

**Comment by michalvasko** [comment]
Hi,
I believe the problem is ODL itself because there are many similar issues to yours, just search a bit. I do not remember whether anyone managed to make it work. Also, it is working in the CLI so I do not know why would it not work for any other client, meaning the problem is probably in the ODL client.

Regards,
Michal

**Comment by LilyCuili** [comment]
Hi,
After change the namespace of private model, I can get the notification from ODL client.
so guess if there is some limitation in the style of namespace  "http://www.netcom.com/yang/rdvp/upgrade".

**Comment by michalvasko** [comment]
Hi,
I do not know about any such limitation in our software, what exactly was the change?

Regards,
Michal

**Comment by LilyCuili** [comment]
change namespace from "http://www.netcom.com/yang/rdvp/upgrade" to urn:sysrepo:upgrade,then from ODL can get the notification.

**Comment by michalvasko** [comment]
Right, and I suppose it worked for both namespaces if you used *netopeer2-cli*. In that case you should report the bug to them.

Regards,
Michal

**Comment by LilyCuili** [comment]
can revieve by subscribe all
