### ISSUE TITLE
scripts not being copied to install path

### ISSUE THREAD

**Issue by iGovindY** [CESNET/netopeer2#730]
Hi 

`make install DESTDIR=/some/other/path/` should copy `setup.sh` and other scripts to the DESTDIR path, right?

Looks that is missing, is this intentional?

Thanks
Govind.

**Comment by michalvasko** [comment]
Hi,
the scripts are not meant to be copied anywhere by default, they are simply executed as part of `make install`. They are separate script files because in some cases (cross-compilation, for example) you want to execute them later. This way you can easily copy them whenever you want and execute them manually.
