### ISSUE TITLE
How Netopeer2 APP can close a NETCONF Session

### ISSUE THREAD

**Issue by robbynet** [CESNET/netopeer2#745]
Hello,
Wonder how a simple Netopeer2 APP, so just linked with lib yang and lib sysrepo can engage the disconnection of a NETCONF Session, knowing that the APP is aware of the Session ID via sysrepo.

**Comment by michalvasko** [comment]
Well, the only possibility is to use `kill-session` RPC because you want to disconnect a session that you have not created. Also, it may not be that simple because you want to work with NETCONF sessions, which are using NETCONF protocol that is one layer higher than your app, which is on *sysrepo* layer.

**Comment by robbynet** [comment]
Got it, thanks for the support
