### ISSUE TITLE
How to user ssh public/private key as authentication method

### ISSUE THREAD

**Issue by morganzhh** [CESNET/Netopeer2#79]
Hi,

I searched the issue list, no related issues about this.

Could someone help to tell me how to specific Netopeer2 server to accept public key?
Also how to tell netopeer-cli to use specific private key file?

Thanks a lot

**Comment by michalvasko** [comment]
Hi,
there is no information about this because it is not finished (devel-server branch). Technically, it is finished and should work, but needs a bit more testing and, as you noted, documentation. However, other issues appeared and this was currently put on hold. So, if you want to try it now, I can only tell you to study the models for NETCONF server and try to figure it out, in CLI simply use `help` and go from there.

Regards,
Michal

**Comment by morganzhh** [comment]
Thanks
