### ISSUE TITLE
netopeer2-cli usage

### ISSUE THREAD

**Issue by ramukima** [CESNET/Netopeer2#87]
Is there a documentation on how to use it in general ?

My specific case is about edit-config complaining all the time -

```
> edit-config --target running --config test.xml --defop merge --test set --error stop
cmd_editconfig: Unparsed command arguments.
edit-config [--help] --target running|candidate --config [<file>] [--defop merge|replace|none] [--test set|test-only|test-then-set] [--error stop|continue|rollback]
```

test.xml
```
<config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
          <foo xmlns="urn:test:foo">
             <id>1</id>
             <name>foo</name>
          </foo>
</config>
```

Not sure whats the issue here. Also, when I try to send RPC payload from a connected session over SSH with terminator '>]]>]]', I do not see any response coming after "hello" message. It will be useful to document the usage for netconf over ssh as well for netopeer2-server.

**Comment by michalvasko** [comment]
Hi,
the problem with the arguments is that `test.xml` is understood as a normal positional argument, not a parameter of `config` (because the parameter is not mandatory). It should be fixed when you type instead `--config=test.xml`. As for the other question, I have actually tried communicating with **netopeer2-server** using **ssh** utility and paste the NETCONF messages manually and it worked. If you mean document how to communicate using NETCONF over SSH, there are RFCs that should be clear enough.

Regards,
Michal

**Comment by ramukima** [comment]
config=test.xml worked. Thank you, I should have looked at the code.

Regarding the usage, here are the things I am doing -
1. ssh netconf@127.0.0.1 -p 830 -s netconf
2. Server responds with hello message and capabilities
3. I type the following sequence:
```
# CR
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><capabilities><capability>urn:ietf:params:netconf:base:1.1</capability></capabilities></hello>
# CR
]]>]]>
```
4. Result: No response from server (expected ?)
5. I type the following sequence:
```
# CR
<rpc message-id="101" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><get-config><source><running/></source></get-config></rpc>
# CR
]]>]]>
```
6. Result: No response from server

As per the RFC, I think the 'terminal' char sequence I send it correct one. Please suggest.

**Comment by ramukima** [comment]
What is a way to delete items from running configuration ? I tried edit-config with defop=none and an XML with 'operation=delete' attributes. The server says operation not supported.

**Comment by michalvasko** [comment]
Hi,
as for communicating with **netopeer2-server** using **ssh**, the first message seems ok (except those CR, I am not sure why you wrote those), so the server should print that a new session was created. As for the RPC request, in the `hello` message you declared you support NETCONF 1.1, so that is what you need to use (a different message format).

Regarding your second issue, please send the full XML and then maybe I can help.

Regards,
Michal
