### ISSUE TITLE
O-ran yang model capabilities are not shown along with ietf yang model  in status message when client is connected to server

### ISSUE THREAD

**Issue by Abrahamma97** [CESNET/netopeer2#871]
Hi @michalvasko,
O-ran yang model capabilities are not shown along with ietf yang model  in status message when client is connected to server.
As per present scenario we can only see ietf capabilities and not o-ran. Is there any particular reason.Also can you tell me how to overcome this?

**Comment by michalvasko** [comment]
My guess is that the reason is your O-RAN modules being YANG 1.1 modules, they are not communicated in the `hello` message so they do not show up in the capabilities. Instead, they are included in `yang-library` data that are retrieved at the beginning as well so your modules are properly loaded most likely, they are just not in the capabilities.

**Comment by Abrahamma97** [comment]
Yes your guess is right. Is there any way to communicate theO-ran Modules in the hello message?

**Comment by michalvasko** [comment]
No, because it is [explicitly forbidden](https://tools.ietf.org/html/rfc7950#page-12).

**Comment by Abrahamma97** [comment]
Noted so concluding with the same reason. Closing the same.
Thanks @michalvasko
