### ISSUE TITLE
sysrepo reconnect

### ISSUE THREAD

**Issue by rkrejci** [CESNET/Netopeer2#89]
Netopeer2 server, as other sysrepo clients, should be able to properly react to the situation when the sysrepo daemon unexpectedly died. In such a case it is needed to reconnect to the daemon.

Sysrepo should have (somewhere) an example code to handle this.

**Comment by mislavn** [comment]
@rkrejci how hard would it be to implement this in Sysrepo under the hood?

**Comment by michalvasko** [comment]
Hi,
it seems *sysrepod* stores any subscriptions in the repository, in separate module persist files. So, upon *sysrepod* restart, they should be possible to be reused by *netopeer2* meaning the restart will be transparent for it. However, the same is not true for sessions or connections. So, *sysrepo* does not probably require any changes except maybe writing a short text about what to do if you want to properly react to `SR_ERR_DISCONNECT`, which can be returned by any *sysrepo* call. You must discard and create connections and sessions anew but you can keep the subscriptions, which is left to implement in *netopeer2*. Right?

Regards,
Michal

**Comment by mislavn** [comment]
Hi,

your right. What do you thin, should we make a Sysrepo reconnect API which could reuse the session and connection (if it is possible) or just add documentation and Sysrepo examples?

Regards,
Mislav

**Comment by michalvasko** [comment]
Hi Mislav,
that is the problem, since *sysrepo* does not store any persistent information about connections and sessions, once it restarts, it cannot communicate on those connections and sessions anymore, so clients cannot reuse them, they must create new ones. I am thinking it should be enough to add documentation, there is not much to put in examples, free all the sessions and connections and create new ones.

Regards,
Michal

**Comment by mislavn** [comment]
Hi Michal,

I agree with creating example code, I just taught we could add the `sr_reconnect` function from the example below to the Sysrepo public API.

The example could look something like this:

```
if (SR_ERR_DISCONNECT != rc) {
     // run this in a loop
     rc = sr_reconnect();
} else if  (SR_ERR_OK != rc) {
     //TODO handle error
}
```

```
sr_reconnect(sr_session_ctx_t *sess) {
    // extract app_name from connection
    // extract datastore and options from session
    // clean sess struct, set members to NULL/0
    // clean conn struct, set members to NULL/0
    rc = sr_connect()
    rc = sr_session_start()
}
```

What do you think about making something like this?

**Comment by michalvasko** [comment]
Hi Mislav,
I understand now what you mean, but I think these new API functions would not simplify anything for the user. For one, you would have to have one such function for *connections*, one for *sessions*, because both are used in an application. Secondly, it is not possible to extract anything from the old structures, no input parameters are stored in them (I have just checked). So, `sr_reconnect()` would look like this

```C
void
sr_reconnect(sr_conn_ctx_t *old_connection, <exact same sr_connect() parameters>)
{
  sr_disconnect(old_connection);
  <exact same sr_connect() code>
}
```
which seems pointless to me.

Regards,
Michal

**Comment by mislavn** [comment]
Hi Michal,

ok, I'll do just the example then.

By the way, how hard would it be to implement Sysrepo reconnect in Netopeer2?

Regards,
Mislav

**Comment by michalvasko** [comment]
Hi Mislav,
I will add this support to netopeer2, should not be too difficult.

Regards,
Michal

**Comment by michalvasko** [comment]
Hi,
this feature proved to be quite difficult to implement correctly, but hopefully it is finished and working.

During netopeer2 startup nothing changed, if the server fails to connect to sysrepo, it will refuse to start. However, if the connection to sysrepo is lost during operation, a reconnect is attempted. If it succeeds, it all happens transparently for the NETCONF client. If not, the client is informed about the problem and the NETCONF session and netopeer2 keep running. Reconnect is tried on every next communication with sysrepo and once it succeeds, normal operation is resumed.

Like I said ([#182](https://github.com/CESNET/Netopeer2/issues/182)), I think keeping the server on while it is not able to reconnect to sysrepo seems useless to me, but I had it almost finished when I realized it, so there it is.

Regards,
Michal
