### ISSUE TITLE
When pattern contains special characters,module can not be loaded.

### ISSUE THREAD

**Issue by zzyyll2** [CESNET/Netopeer2#90]
yang like this,
```
module test {
    namespace "urn:local:params:xml:ns:yang:test";
	prefix test;
	container Root {			
        leaf name {
			type typeName;
		}		
	}		
    typedef typeName {
        type string {
            length "0..128";
            pattern "^[^&'\\"<>]*$";
        }    
    }
}
```
sysrepoctl -i -g test.yang, it's ok
login in netpeer2-cli, 
send command:   get-schema --model test
show error :
```
ERROR
	type:     application
	tag:      invalid-value
	severity: error
	message:  The requested schema was not found.
```

**Comment by michalvasko** [comment]
Hi,
it should be fixed now, but I encountered another problem that will be fixed a bit later. Your pattern is invalid because in YANG encoding `\\` is decoded into `\`, so the following double-quote ends the string and the following characters should fail to be parsed. Currently, it is parsed as if the pattern was `^[^&'\\\"<>]*$`, which I assume is what you meant, but this is wrong.

Regards,
Michal

**Comment by zzyyll2** [comment]
my means is pattern "^[^&'\"<>]*$",but at first the editor show "^[^&'"<>]*$",so i add \ twice.
thanks.

**Comment by zzyyll2** [comment]
Oops,something is wrong with this text input editor.

**Comment by zzyyll2** [comment]
It solved my problem,thanks again.
