### ISSUE TITLE
Question related to netopeer2-server rpc-reply messages when sysrepo is not running?

### ISSUE THREAD

**Issue by Roky7250** [CESNET/netopeer2#909]
Hi, I have question related to netopeer2-server.

I have few modules developed in sysrepo and they have their purpose, setting some things on the device via NETCONF.
When netopeer2-server and sysrepo are started, I connect to the netopeer2-server and send some rpc messages, that contain some edit-config operations to the running datastore. Sysrepo is triggering callbacks and that configuration is applied to the device. netopeer2-server will return OK if everything goes fine.

But when sysrepo is crashed for some reason and netopeer2-server is running I get an OK response from the server when sending some edit-config requests even though sysrepo is not running and callbacks are not triggered.
I saw that there is a flag on netopeer2-cli that I can set to some value, and configuration will not be applied if some error happened, by error mean that sysrepo is not running. 
When I set that flag configuration will not be applied, but I still get an OK message from the server. I can see that configuration is not applied because my running datastore does not contain changes that I made.

So my question is: Is there any way that netopeer2-server returns some error message that will say that sysrepo is not running and configuration (changes) will not be applied?

Or I need to verify that using this flag and checking configuration inside running datastore.
I could create a hash from the configuration that I am sending. After edit-config I could call get-config, hash it and check if hashes are the same. That will mean that configuration is applied, otherwise not.

Regards

**Comment by michalvasko** [comment]
> sysrepo are started

Firstly, this is quite inaccurate because you cannot start "sysrepo", you can only start your own *sysrepo* application that subscribes to certain changes.

But to answer you, in NMDA you can modify configuration without it being applied anywhere so *sysrepo* supports that. You learn that it is not applied by querying the `operational` datastore. There is also `sysrepo-monitoring` module whose operational data you can request and then examine whether there are specific subscriptions you are interested in.
