### ISSUE TITLE
nacm about rule path contains augment node

### ISSUE THREAD

**Issue by super-casper** [CESNET/netopeer2#918]
Hello,

I set a rule like this:

      <enable-nacm>true</enable-nacm>
      <read-default>deny</read-default>
      <write-default>deny</write-default>
      <exec-default>permit</exec-default>
      <groups>
        <group>
          <name>G1</name>
          <user-name>aaa</user-name>
        </group>
      </groups>
      <rule-list>
        <name>read-syslog</name>
        <group>G1</group>
        <rule>
          <name>read-logging-console</name>
          <module-name>ietf-syslog</module-name>
          <access-operations>read</access-operations>
          <action>permit</action>
          <path xmlns:syslog="urn:ietf:params:xml:ns:yang:ietf-syslog"
                xmlns:syslog-aug="http://www.qct.io/ns/yang/syslog-aug">/syslog:syslog/syslog:buffered-logging-action/syslog-aug:enabled</path>
        </rule>
      </rule-list>

then I use user `aaa` to get the path `/syslog:syslog/syslog:buffered-logging-action/syslog-aug:enabled` will nacm fail  because the path contains augment module `syslog-aug`. It looks like the module name is not match in 

> /* 7) find matching rules */
      for (rule = rlist->rules; rule; rule = rule->next) {
          /* module name matching */
          if (rule->module_name && rule->module_name != lyd_node_module(node)->name) {

Does nacm support path contains augment module or I use wrong operation on nacm?

**Comment by michalvasko** [comment]
If you have a specific path, you do not have to set any `module-name` so that is my suggestion. It should work then. Nevertheless, the correct `module-name` is probably `syslog-aug` although that will not work either but before I fix it somehow I need to be certain. Like I said, you should not use it all and then it should not matter.

**Comment by super-casper** [comment]
Thanks Michal, I will try it and the issue will be fixed in future, right?

**Comment by super-casper** [comment]
Hello Michal, according to your suggestion, it can work now. But this issue will be fixed in future? It seems the replace operation have the same problem.

**Comment by michalvasko** [comment]
Well, yes, it is a problem of matching the module name to the actual module of the nodes but simply omitting it should work. Yes, I will try to fix it once there are no other more serious issues.

**Comment by michalvasko** [comment]
Okay, it should work now.

**Comment by super-casper** [comment]
Hello Michal,

Thanks your help, it can work in this case. But here is another problem... if my rule is:

    <rule>
      <name>read-write-logging-console</name>
      <module-name>ietf-syslog</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
      <path xmlns:syslog="urn:ietf:params:xml:ns:yang:ietf-syslog">/syslog:syslog/syslog:console-logging-action</path>
    </rule>

And I get the path `/syslog:syslog/syslog:buffered-logging-action/syslog-aug:enabled`.
The `get` operation can work because `module name` and `path` can match. But `edit-config` operation can't work because module name in request is `syslog-aug` and the nacm setting is `ietf-syslog`.

And I set module name in nacm as `syslog-aug`:

    <rule>
      <name>read-write-logging-console</name>
      <module-name>syslog-aug</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
      <path xmlns:syslog="urn:ietf:params:xml:ns:yang:ietf-syslog">/syslog:syslog/syslog:console-logging-action</path>
    </rule>

And I get the path `/syslog:syslog/syslog:buffered-logging-action/syslog-aug:enabled`.
The result becomes `get` operation will fail. But `edit-config` operation can work.

**Comment by michalvasko** [comment]
There is not much I can do about this, if it were up to me you would have to choose whether you specify `module-name` or `path`, it makes no sense to specify both because the module prefix must always be in the path. You insist on defining both, which is up to you, but I will not waste time fixing these problems.

I actually believe this is not really defined because on one hand the descendant nodes of the path you specify must match as well and on the other the module name must match, which can change for the descendants, obviously. So I honestly do not know what the behavior should be, I think it now actually works exactly as the standard requires, resulting in this mess.

**Comment by super-casper** [comment]
OK, thanks for your help.
