### ISSUE TITLE
Future netopeer2/sysrepo release plan

### ISSUE THREAD

**Issue by ashishsaxenahsc** [CESNET/netopeer2#955]
Hi Devs ,

How can I get information regarding future netopeer2/sysrepo release plan , and the timelines for the releases ?
Also , do we have any upgrade strategy for upgrading from older to new releases ?

Thanks and Regards,
Ashish

**Comment by michalvasko** [comment]
> How can I get information regarding future netopeer2/sysrepo release plan , and the timelines for the releases ?

You cannot because there is none. We are a very small team that needs to be quite flexible regarding its work so it is difficult to set some specific deadlines. The general strategy is that once there are enough important changes in the `devel` branch of a project, a new release is made and the branch merged into `master`.

> Also , do we have any upgrade strategy for upgrading from older to new releases ?

Not really but it depends a lot on your requirements. The main issue is with upgrading *sysrepo*, the libraries should be seamless and *netopeer2* also, just replacing the binary. If some incompatible changes are made and the data (in shared memory) from the previous version cannot be used, you will get an error (something with shared memory version). To fix, you need to remove all the old data (sysrepo `make sr_clean`). But if you want to keep specific YANG instance data, you can easily back them up (`sysrepocfg --export=backup.xml --datastore startup`) and restore (`sysrepocfg --import=backup.xml --datastore startup`) after the upgrade.

In general, you should be fine with doing the backup/restore steps with each upgrade to keep your data. However, it still depends on how extensive the changes in the new version are. If, for example, the used `ietf-netconf-server` YANG module was updated (which will happen once it is finally published as an RFC), you will not be able to restore the backup because the data will not match. But you can always restore data for the other (your) YANG modules except then you will have to use the `--module` parameter for `sysrepocfg` to limit the operations to that module only.
