### ISSUE TITLE
Support for unsubscribing or cancelling notification subscription 

### ISSUE THREAD

**Issue by ChinmayaAgarwal** [CESNET/netopeer2#993]
Hi,

Is there any RPC support or netopeer2-cli command for cancelling a notification subscription in netopeer2 and sysrepo?

Thanks and Regards,
Chinmaya Agarwal.

**Comment by michalvasko** [comment]
No, there is none because none are defined for the standard notifications from [RFC 5277](https://datatracker.ietf.org/doc/html/rfc5277). However, there are also new notifications defined in [RFC 8639](https://www.rfc-editor.org/rfc/rfc8639) that support deleting subscriptions and that are also supported by *netopeer2-server* v2.
